// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit

export interface PluginContentEntry {
  name: string;
  version: string;
  description?: string;
  icon?: string;
  actionType?: string;
  authRequired?: boolean;
  capabilities: string[];
  artifacts: Array<{ type: string; filename: string; content: string; sortOrder: number }>;
}

export const pluginContentRegistry: PluginContentEntry[] = [
  {
    name: "browser",
    version: "0.0.1",
    description: "Browser control via agent-browser CLI",
    icon: "🌐",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "browser.md", content: `---
name: browser
description: Control the Chromium browser using the agent-browser CLI. Navigate, click, type, fill forms, take snapshots, extract content, and more.
---

# Browser Control via agent-browser CLI

You have \`agent-browser\` installed globally. It controls a real Chromium browser on display \`:99\` (visible in the user's VNC panel).

**Always use \`--headed\` flag** so the browser renders on the VNC display:

\`\`\`bash
agent-browser --headed <command>
\`\`\`

## Core Workflow

1. **Open a URL**: \`agent-browser --headed open <url>\`
2. **Take a snapshot** to see page structure: \`agent-browser --headed snapshot -i -c\`
3. **Interact** using element refs from the snapshot: \`agent-browser --headed click @e3\`
4. **Verify visually**: Use the \`browser_screenshot\` tool to capture the VNC display and show it in chat.

## Navigation

\`\`\`bash
agent-browser --headed open <url>          # Navigate to URL
agent-browser --headed back                # Go back
agent-browser --headed forward             # Go forward
agent-browser --headed reload              # Reload page
agent-browser --headed close               # Close browser
\`\`\`

## Clicking & Focus

\`\`\`bash
agent-browser --headed click <selector>    # Click element (CSS selector or @ref)
agent-browser --headed dblclick <selector> # Double-click
agent-browser --headed focus <selector>    # Focus element
agent-browser --headed hover <selector>    # Hover over element
\`\`\`

## Text Input

\`\`\`bash
agent-browser --headed type <selector> <text>   # Type into element (appends)
agent-browser --headed fill <selector> <text>    # Clear field and fill with text
agent-browser --headed press <key>               # Press key (Enter, Tab, Control+a, etc.)
\`\`\`

## Form Controls

\`\`\`bash
agent-browser --headed select <selector> <value> # Select dropdown option
agent-browser --headed check <selector>           # Check checkbox
agent-browser --headed uncheck <selector>         # Uncheck checkbox
agent-browser --headed upload <selector> <files>  # Upload files
\`\`\`

## Scrolling

\`\`\`bash
agent-browser --headed scroll down [px]           # Scroll down (default ~page)
agent-browser --headed scroll up [px]             # Scroll up
agent-browser --headed scrollintoview <selector>  # Scroll element into view
\`\`\`

## Snapshots (Accessibility Tree)

Snapshots give you a structured view of the page with element refs (\`@e1\`, \`@e2\`, etc.) you can use in subsequent commands.

\`\`\`bash
agent-browser --headed snapshot              # Full accessibility tree
agent-browser --headed snapshot -i           # Interactive elements only
agent-browser --headed snapshot -c           # Compact output
agent-browser --headed snapshot -i -c        # Interactive + compact (recommended)
agent-browser --headed snapshot -d 3         # Limit depth to 3
agent-browser --headed snapshot -s "main"    # Scope to a CSS selector
\`\`\`

After a snapshot, use the \`@ref\` identifiers to interact:

\`\`\`bash
agent-browser --headed click @e3
agent-browser --headed fill @e7 "search query"
\`\`\`

## Getting Page Information

\`\`\`bash
agent-browser --headed get title             # Page title
agent-browser --headed get url               # Current URL
agent-browser --headed get text <selector>   # Text content of element
agent-browser --headed get html <selector>   # innerHTML of element
agent-browser --headed get value <selector>  # Input value
agent-browser --headed get attr <sel> <attr> # Element attribute
agent-browser --headed get count <selector>  # Count matching elements
\`\`\`

## Checking Element State

\`\`\`bash
agent-browser --headed is visible <selector>  # Check visibility
agent-browser --headed is enabled <selector>  # Check if enabled
agent-browser --headed is checked <selector>  # Check if checked
\`\`\`

## Waiting

\`\`\`bash
agent-browser --headed wait <selector>         # Wait for element to appear
agent-browser --headed wait 2000               # Wait 2 seconds
agent-browser --headed wait --text "Success"   # Wait for text to appear
agent-browser --headed wait --url "**/dashboard" # Wait for URL pattern
\`\`\`

**NEVER use \`wait --load networkidle\`** — many sites never reach network idle (analytics, websockets, polling). It will hang indefinitely and can break the session.

## Semantic Finding

Find elements by role, text, label, etc. and perform actions:

\`\`\`bash
agent-browser --headed find role button click              # Click first button
agent-browser --headed find text "Submit" click            # Click element with text
agent-browser --headed find label "Email" fill "a@b.com"   # Fill by label
agent-browser --headed find placeholder "Search" fill "q"  # Fill by placeholder
agent-browser --headed find testid "login-btn" click       # Click by data-testid
\`\`\`

## Tabs

\`\`\`bash
agent-browser --headed tab                   # List open tabs
agent-browser --headed tab new [url]         # Open new tab
agent-browser --headed tab 2                 # Switch to tab 2
agent-browser --headed tab close [n]         # Close tab
\`\`\`

## JavaScript Evaluation

\`\`\`bash
agent-browser --headed eval "document.title"
agent-browser --headed eval "window.scrollTo(0, document.body.scrollHeight)"
\`\`\`

## Dialogs

\`\`\`bash
agent-browser --headed dialog accept [text]  # Accept alert/confirm/prompt
agent-browser --headed dialog dismiss        # Dismiss dialog
\`\`\`

## Cookies & Storage

\`\`\`bash
agent-browser --headed cookies               # List cookies
agent-browser --headed cookies clear         # Clear cookies
agent-browser --headed storage local         # List localStorage
agent-browser --headed storage local <key>   # Get specific key
\`\`\`

## Common Workflow Examples

### Navigate and extract content

\`\`\`bash
timeout 15 agent-browser --headed open "https://example.com"
agent-browser --headed snapshot -i -c
agent-browser --headed get title
\`\`\`

### Fill a form

\`\`\`bash
timeout 15 agent-browser --headed open "https://example.com/login"
agent-browser --headed snapshot -i -c
timeout 10 agent-browser --headed fill @e3 "user@example.com"
timeout 10 agent-browser --headed fill @e5 "password123"
timeout 15 agent-browser --headed click @e7
agent-browser --headed wait 2000
agent-browser --headed snapshot -i -c
\`\`\`

### Using snapshot refs

\`\`\`bash
agent-browser --headed open "https://news.ycombinator.com"
agent-browser --headed snapshot -i -c
# Output shows refs like @e1, @e2, @e3...
agent-browser --headed click @e5    # Click the 5th interactive element
agent-browser --headed get title    # Verify navigation
\`\`\`

## Avoiding Hangs

Browser commands can hang if a page never finishes loading or a click triggers an unexpected navigation. **Always wrap browser commands with \`timeout\`** to prevent blocking the session:

\`\`\`bash
timeout 15 agent-browser --headed click @e3
timeout 15 agent-browser --headed open "https://example.com"
timeout 15 agent-browser --headed fill @e7 "text"
\`\`\`

Use \`timeout 15\` (15 seconds) as a sensible default. If a command times out, take a snapshot to see what happened and adjust your approach.

**Never use \`wait --load networkidle\`** — it hangs on most real-world sites. Instead, wait for specific elements:

\`\`\`bash
timeout 10 agent-browser --headed wait "input[name=email]"  # Wait for a specific element
timeout 10 agent-browser --headed wait --text "Welcome"     # Wait for specific text
\`\`\`

## Tips

- **Always take a screenshot** with \`browser_screenshot\` after navigating or clicking so you and the user can see the result.
- Use \`snapshot -i -c\` as your go-to for understanding page structure.
- Prefer \`fill\` over \`type\` for form fields (it clears first).
- The browser persists between commands within a session. No need to reopen it.
- If the browser isn't running, \`agent-browser --headed open <url>\` will start it.
`, sortOrder: 0 },
    ],
  },
  {
    name: "cloudflare",
    version: "0.0.1",
    description: "Cloudflare integration for DNS, zones, and workers",
    icon: "☁️",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "deepwiki",
    version: "0.0.1",
    description: "DeepWiki integration for repository knowledge base",
    icon: "📚",
    authRequired: false,
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "github",
    version: "0.0.1",
    description: "GitHub integration for PRs, issues, repos, and webhooks",
    icon: "🐙",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "gmail",
    version: "0.0.1",
    description: "Gmail integration for reading and sending emails",
    icon: "📧",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "google-calendar",
    version: "0.0.1",
    description: "Google Calendar integration for events and scheduling",
    icon: "📅",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "google-docs",
    version: "0.0.1",
    description: "Google Docs integration with markdown-native read/write",
    icon: "📝",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "google-drive",
    version: "0.0.1",
    description: "Google Drive integration for files and documents",
    icon: "📁",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "google-sheets",
    version: "0.0.1",
    description: "Google Sheets integration for spreadsheet operations",
    icon: "📊",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "linear",
    version: "0.0.1",
    description: "Linear integration for issue tracking and project management",
    icon: "🎯",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "memory-compaction",
    version: "0.0.1",
    description: "Memory compaction plugin for OpenCode",
    icon: "🧠",
    capabilities: ["tools"],
    artifacts: [
      { type: "tool", filename: "memory-compaction.ts", content: `export default async () => {
  return {
    "experimental.session.compacting": async (_input: unknown, output: { context: string[] }) => {
      output.context.push(\`
COMPACTION INSTRUCTIONS — follow exactly before writing your summary:

Your summary must contain these sections. Do NOT omit any of them.
Anything not captured here is permanently lost after compaction.

## Active Work
- Task(s) currently in progress (what, status, what's blocking)
- Child session IDs and their last known status
- What the user is waiting for (if anything)

## Key Decisions Made
- Architectural, process, or preference decisions from this session
- Any constraints or bugs discovered

## Artifacts Created
- Branches, PRs, commits, files changed (include identifiers like PR #N, branch name, commit SHA)

## Things to Remember
- Repo URLs learned this session
- User preferences stated this session
- Project facts discovered (stack, conventions, etc.)

## Resume Instructions
When you resume after this compaction, your FIRST action must be:
1. Call mem_patch to write a journal entry summarizing the above:
   mem_patch("journal/YYYY-MM-DD.md", [{ op: "append", content: "\\\\n\\\\n## [time] — Resumed after compaction\\\\n[paste Active Work + Artifacts here]" }])
2. Check on any child sessions that were running (use get_session_status)
3. Then continue whatever was in progress

Do not respond to the user before completing step 1.
\`);
    },
  };
};
`, sortOrder: 0 },
    ],
  },
  {
    name: "notion",
    version: "0.0.1",
    description: "Notion integration for pages, databases, and workspaces",
    icon: "📝",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "personas",
    version: "0.0.1",
    description: "Agent persona and skill management",
    icon: "🎭",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "personas.md", content: `---
name: personas
description: Create and configure agent personas with attached skills. Manage the skill library and understand skill sources.
---

# Persona & Skill Management

## Concepts

### Skills

Skills are markdown documents that teach agents how to perform specific tasks. Every skill has a **source** that determines where it came from and whether you can edit it:

| Source | What it is | Editable? | Example |
|--------|-----------|-----------|---------|
| \`builtin\` | Platform-shipped skills | No | browser, workflows |
| \`plugin\` | Skills from installed extensions | No | custom org plugins |
| \`managed\` | Skills created by users or agents | Yes (owner only) | "deploy-checklist", "code-review-frontend" |

Skills also have **visibility**:
- \`private\` — only the creator can see and use it
- \`shared\` — visible to the entire org

### Personas

Personas are instruction sets that customize agent behavior. A persona has:
- **Name and icon** — human-readable identity
- **Instructions** — system prompt markdown that defines the agent's role and behavior
- **Attached skills** — skills that auto-load when a session starts with this persona

### How skills reach an agent session

When a session starts, the system loads skills in this order:
1. If the session has a **persona** → load skills attached to that persona
2. If no persona → load **org default skills**
3. Agent can always **search and read** additional skills on demand from the full library

This means attaching a skill to a persona guarantees it's in the agent's context from the first message — no searching needed.

## Common Workflows

### Creating a specialized agent

1. **Create skills** for the agent's domain knowledge:
   \`\`\`
   create_skill(name: "Frontend Code Review", content: "# Frontend Review Standards\\n\\n...")
   \`\`\`

2. **Create a persona** with role instructions:
   \`\`\`
   create_persona(name: "Frontend Reviewer", icon: "🔍", instructions: "You are a frontend code reviewer...")
   \`\`\`

3. **Attach skills** to the persona:
   \`\`\`
   attach_skill_to_persona(personaId: "<persona-id>", skillId: "<skill-id>")
   \`\`\`

4. **Spawn a session** with the persona (from orchestrator):
   \`\`\`
   spawn_session(task: "Review PR #42", persona_id: "<persona-id>", ...)
   \`\`\`

### Inspecting a persona's configuration

\`\`\`
list_persona_skills(personaId: "<persona-id>")
\`\`\`

Returns all attached skills with their source, description, and sort order.

### Reusing existing skills

Before creating a new skill, search the library:
\`\`\`
search_skills(query: "code review")
\`\`\`

You can attach builtin or plugin skills to personas — they don't need to be managed. Any skill from any source can be attached.

### Updating a persona's skill set

- **Add a skill:** \`attach_skill_to_persona(personaId, skillId)\`
- **Remove a skill:** \`detach_skill_from_persona(personaId, skillId)\`
- **Reorder:** Re-attach with a different \`sortOrder\` — attaching an already-attached skill updates its sort order (lower = loaded first)

## Tool Reference

| Tool | Purpose |
|------|---------|
| \`create_persona\` | Create a new persona with name, icon, instructions |
| \`update_persona\` | Update persona metadata or instructions |
| \`delete_persona\` | Remove a persona |
| \`list_personas\` | List all available personas |
| \`create_skill\` | Create a managed skill |
| \`update_skill\` | Update a managed skill's content |
| \`delete_skill\` | Delete a managed skill |
| \`search_skills\` | Search the skill library by keyword |
| \`read_skill\` | Read a skill's full content |
| \`attach_skill_to_persona\` | Attach a skill to a persona |
| \`detach_skill_from_persona\` | Detach a skill from a persona |
| \`list_persona_skills\` | List skills attached to a persona |

## Tips

- **Visibility defaults differ:** Skills default to \`private\`, personas default to \`shared\`. Set visibility explicitly when creating.
- **Sort order matters:** Skills load in sort order. Put foundational skills (coding standards, conventions) at lower sort orders so they appear first in context.
- **Managed skills only:** You can only edit/delete skills with \`source: managed\`. Builtin and plugin skills are read-only, but you can still attach them to personas.
- **Skill content format:** Use YAML frontmatter for metadata (tags, version) followed by markdown content. The content is what gets loaded into the agent's context.
`, sortOrder: 0 },
    ],
  },
  {
    name: "sandbox-tunnels",
    version: "0.0.1",
    description: "Sandbox tunnel management",
    icon: "🔗",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "sandbox-tunnels.md", content: `---
name: sandbox-tunnels
description: Expose sandboxed services via public Cloudflare Quick Tunnels. Each tunnel gets a unique hostname with no path prefix — apps work as if hosted at root.
---

# Sandbox Tunnels

## Goal
Expose sandboxed services through public Cloudflare Quick Tunnels. Each tunnel gets its own unique \`*.trycloudflare.com\` hostname — no path prefix, no base URL configuration needed.

## Quick Path
1. Start services bound to \`0.0.0.0\` inside the sandbox.
2. Register tunnels via \`register_tunnel\`.
3. Use the returned public URL directly — no CORS, no base path.

## Tunnel Workflow
1. Start backend:
   - Example: \`python backend.py --host 0.0.0.0 --port 3000\`
2. Start frontend:
   - Example: \`pnpm dev --host 0.0.0.0 --port 3001\`
3. Register tunnels:
   - \`register_tunnel { name: "api", port: 3000 }\`
   - \`register_tunnel { name: "frontend", port: 3001 }\`
4. Each tunnel returns a unique public URL like \`https://random-words.trycloudflare.com\`
5. Share the URL — no token or auth needed for public access.

## Key Differences from Gateway Tunnels
- **No path prefix**: Apps are served at \`/\`, not \`/t/<name>/\`.
- **No base path config**: No need to set \`base\`, \`basePath\`, \`PUBLIC_URL\`, or \`assetPrefix\`.
- **No JWT/token**: Cloudflare Quick Tunnels are publicly accessible (no gateway auth).
- **Independent hostnames**: Each tunnel is a separate origin — no CORS between tunnels.

## Cross-Origin Between Tunnels
Since each tunnel is its own origin, frontend-to-backend calls are cross-origin. Options:
- **Enable CORS** on the backend (recommended for APIs).
- **Proxy through the frontend** (e.g., Vite proxy, Next.js rewrites).
- **Use the gateway fallback**: The old \`/t/<name>\` paths still work through the gateway for same-origin access.

## Frontend Integration
\`\`\`js
// Use the tunnel URL directly
const API_URL = "https://backend-words.trycloudflare.com"
fetch(\`\${API_URL}/health\`)

// Or set via environment variable
// API_URL=https://backend-words.trycloudflare.com
\`\`\`

## WebSocket Support
Cloudflare Quick Tunnels support WebSockets natively:
\`\`\`js
const ws = new WebSocket("wss://backend-words.trycloudflare.com/ws")
\`\`\`

## Debugging Checklist
- \`ss -tlnp | rg <port>\`: confirm service is listening on 0.0.0.0.
- \`curl -sS http://127.0.0.1:<port>/health\`: confirm service responds locally.
- If tunnel URL returns 502, the local service isn't reachable on that port.
- \`list_tunnels\` to see all active tunnels and their URLs.

## Deleting Tunnels
- \`unregister_tunnel { name: "api" }\` kills the cloudflared process.
- Users can also delete tunnels from the session UI.

## Gateway Fallback
The gateway \`/t/<name>\` paths still work for same-origin access within the sandbox. These require JWT auth and are useful for internal service-to-service calls.

## API Access
- \`GET /api/sessions/:id/tunnels\` → \`{ gatewayUrl, tunnels }\` (tunnels include cloudflared URLs)
`, sortOrder: 0 },
    ],
  },
  {
    name: "sentry",
    version: "0.0.1",
    description: "Sentry integration for error tracking and monitoring",
    icon: "🐛",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "slack",
    version: "0.0.1",
    description: "Slack integration for actions (messages, channels, users) and channel transport",
    icon: "💬",
    capabilities: ["actions","channels"],
    artifacts: [],
  },
  {
    name: "stripe",
    version: "0.0.1",
    description: "Stripe integration for payments, customers, and subscriptions",
    icon: "💳",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "telegram",
    version: "0.0.1",
    description: "Telegram bot messaging and transport",
    icon: "📱",
    capabilities: ["channels"],
    artifacts: [],
  },
  {
    name: "typefully",
    version: "0.0.1",
    description: "Typefully integration for social media content management",
    icon: "📝",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "workflows",
    version: "0.0.1",
    description: "Workflow lifecycle and operations",
    icon: "🔄",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "workflows.md", content: `---
name: workflows
description: End-to-end Valet workflow operations. Use when creating, updating, deleting, running, scheduling, debugging, rolling back, or self-modifying workflows; when managing workflow executions and approvals; when configuring trigger behavior; when passing repository context into workflow runs; and when using agent_message workflow steps.
---

# Workflows

## Use the workflow tools, not raw API calls

Use these tools for lifecycle operations:

- \`list_workflows\`, \`get_workflow\`, \`sync_workflow\`, \`update_workflow\`, \`delete_workflow\`
- \`list_workflow_history\`, \`rollback_workflow\`
- \`list_workflow_proposals\`, \`create_workflow_proposal\`, \`review_workflow_proposal\`, \`apply_workflow_proposal\`
- \`run_workflow\`, \`list_workflow_executions\`, \`get_execution\`, \`get_execution_steps\`, \`debug_execution\`, \`approve_execution\`, \`cancel_execution\`
- \`list_triggers\`, \`sync_trigger\`, \`run_trigger\`, \`delete_trigger\`

## Think in 4 layers

1. Workflow definition: versioned JSON with non-empty \`steps\`.
2. Trigger configuration: dispatch rules for \`manual\`, \`webhook\`, or \`schedule\`.
3. Execution record: immutable run state, status, step traces, and approval token lifecycle.
4. Workflow session: dedicated sandbox session (\`purpose: workflow\`) started/woken by the workflow executor.

## Choose the right lifecycle tool

- Use \`sync_workflow\` for create or full-definition upsert.
- Use \`update_workflow\` for partial metadata/definition patch (\`name\`, \`description\`, \`slug\`, \`version\`, \`enabled\`, \`tags\`, \`data\`).
- Use \`delete_workflow\` to remove workflows (and linked triggers).
- Use \`list_workflow_history\` before rollback or forensic comparison.
- Use \`rollback_workflow\` with a \`target_workflow_hash\` from history.

## Use proposal flow for self-modifying workflows

Follow this sequence:

1. Use \`get_workflow\` and compute/use current workflow hash as \`base_workflow_hash\`.
2. Use \`create_workflow_proposal\`.
3. Use \`review_workflow_proposal\` (\`approve=true/false\`).
4. Use \`apply_workflow_proposal\` after approval.

Notes:

- Proposal creation enforces base-hash matching.
- Workflow must allow self-modification (\`constraints.allowSelfModification === true\`).
- Use \`list_workflow_proposals\` to inspect status transitions (\`pending\`, \`approved\`, \`rejected\`, \`applied\`, \`failed\`).

## Run and operate executions

Run:

- Use \`run_workflow\` with \`workflow_id\`.
- Optionally pass \`variables_json\`.
- Optionally pass repo context: \`repo_url\`, \`repo_branch\`, \`repo_ref\`, \`source_repo_full_name\`.

Inspect:

- Use \`list_workflow_executions\` for recent runs.
- Use \`get_execution\` for authoritative status and current \`resumeToken\`.
- Use \`get_execution_steps\` for ordered normalized step traces.
- Use \`debug_execution\` first when a run stalls/fails.

Approval/cancel:

- Use \`approve_execution\` with the latest \`resume_token\` from \`get_execution\`.
- Use \`cancel_execution\` for stuck/inconsistent runs.

## Configure triggers and scheduling

Use \`sync_trigger\` for create/update:

- \`type=manual\`
- \`type=webhook\` requires \`webhook_path\` (optional method/secret)
- \`type=schedule\` requires \`schedule_cron\`

Schedule specifics:

- \`schedule_cron\` must be a 5-field cron expression.
- \`schedule_timezone\` uses IANA TZ names.
- \`schedule_target=workflow\` (default): dispatches workflow execution.
- \`schedule_target=orchestrator\`: dispatches \`schedule_prompt\` to orchestrator session.
- \`schedule_prompt\` is required when \`schedule_target=orchestrator\`.

Use \`run_trigger\` to test behavior immediately.

Use \`delete_trigger\` to remove stale triggers.

Variable mapping note:

- Keep \`variable_mapping_json\` paths simple (\`$.field\`), since extraction is shallow.

## Understand workflow execution context

Workflow runs do not execute in the orchestrator sandbox.

Execution context behavior:

1. A workflow session is created as a dedicated session (\`purpose: workflow\`) and initially hibernated.
2. \`WorkflowExecutorDO\` wakes/boots that workflow sandbox when enqueue/resume happens.
3. The executor dispatches a workflow-run prompt into that workflow session.

Repository context behavior:

- Repo context is stored in \`session_git_state\` for the workflow session.
- Executor injects \`REPO_URL\`, \`REPO_BRANCH\`, \`REPO_REF\` env vars into the sandbox.
- Sandbox startup clones \`REPO_URL\` into \`/workspace/<repo>\`, checks out branch/ref when provided, and sets working directory to the clone.

## Author workflow definitions with current runtime behavior

Minimum requirement:

- \`workflow.steps\` must be a non-empty array.
- Each step must have \`id\` (string), \`name\` (string), and \`type\` (string).

Valid step types: \`bash\`, \`tool\`, \`approval\`, \`conditional\`, \`parallel\`, \`agent\`, \`agent_message\`.

### \`bash\` step (preferred for shell commands)

Use \`type: "bash"\` for shell commands. This is a first-class step type.

Required fields:
- \`command\` (string): The shell command to execute.

Optional fields:
- \`description\` (string): Human-readable description of what this command does.
- \`cwd\` (string): Working directory.
- \`timeoutMs\` (number): Timeout in milliseconds (default 120000, max 600000).
- \`outputVariable\` (string): Variable name to store command output.

Example:
\`\`\`json
{
  "id": "1",
  "name": "Run tests",
  "type": "bash",
  "command": "npm test",
  "description": "Run the test suite"
}
\`\`\`

**Do NOT use \`type: "tool"\` with \`tool: "bash"\` for shell commands.** Use \`type: "bash"\` instead.

### \`tool\` step

For non-bash tools only. Requires \`tool\` (string) and optionally \`arguments\` (object).

### \`approval\` step

Pauses execution and waits for human approval.

Optional fields:
- \`prompt\` (string): Message shown to the approver.

### \`conditional\` step

Evaluates a condition and runs \`then\` or \`else\` branch.

Required fields:
- \`condition\`: Boolean value, or object like \`{ "variable": "varName", "equals": "value" }\`.

Optional fields:
- \`then\` (array of steps): Steps to run when condition is true.
- \`else\` (array of steps): Steps to run when condition is false.

### \`parallel\` step

Runs nested steps. Requires \`steps\` (array of steps).

### \`agent\` step

Dispatches work to an AI agent.

Optional fields:
- \`goal\` (string): What the agent should accomplish.
- \`context\` (string): Additional context for the agent.

### \`agent_message\` step

Sends a message to the workflow session agent.

Required: Provide message via \`content\` (preferred), or \`message\`, or \`goal\`.

Optional fields:
- \`interrupt\` (boolean).
- \`await_response\` (or \`awaitResponse\`) boolean.
- \`await_timeout_ms\` (or \`awaitTimeoutMs\`) number, minimum 1000.

Behavior:
- Non-await mode sends a message to the current workflow session agent.
- Await mode runs a temporary OpenCode session and returns response text in step output.

### Complete workflow example

\`\`\`json
{
  "steps": [
    {
      "id": "1",
      "name": "Install dependencies",
      "type": "bash",
      "command": "npm install",
      "description": "Install project dependencies"
    },
    {
      "id": "2",
      "name": "Run linter",
      "type": "bash",
      "command": "npm run lint",
      "description": "Check code quality"
    },
    {
      "id": "3",
      "name": "Run tests",
      "type": "bash",
      "command": "npm test",
      "outputVariable": "test_results"
    },
    {
      "id": "4",
      "name": "Approve deployment",
      "type": "approval",
      "prompt": "Tests passed. Deploy to production?"
    },
    {
      "id": "5",
      "name": "Deploy",
      "type": "bash",
      "command": "npm run deploy"
    }
  ]
}
\`\`\`

## Reliable operating playbook

1. Use \`list_workflows\` and \`list_triggers\` before creating/updating to avoid duplicates.
2. Use \`get_workflow\` before patching critical definitions.
3. Use \`run_workflow\` or \`run_trigger\` for tests.
4. Use \`debug_execution\` first for incidents.
5. Use fresh \`resume_token\` from \`get_execution\` before \`approve_execution\`.
6. Use \`cancel_execution\` when state is inconsistent, then rerun cleanly.
7. Use \`list_workflow_history\` and \`rollback_workflow\` for safe recovery.
`, sortOrder: 0 },
    ],
  },
];
