// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit

export interface PluginContentEntry {
  name: string;
  version: string;
  description?: string;
  icon?: string;
  actionType?: string;
  authRequired?: boolean;
  capabilities: string[];
  artifacts: Array<{ type: string; filename: string; content: string; sortOrder: number }>;
}

export const pluginContentRegistry: PluginContentEntry[] = [
  {
    name: "1password",
    version: "0.0.1",
    description: "Secret management for agent sessions",
    icon: "🔑",
    capabilities: [],
    artifacts: [],
  },
  {
    name: "browser",
    version: "0.0.1",
    description: "Browser control via agent-browser CLI",
    icon: "🌐",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "browser.md", content: `---
name: browser
description: Control the Chromium browser using the agent-browser CLI. Navigate, click, type, fill forms, take snapshots, extract content, and more.
---

# Browser Control via agent-browser CLI

You have \`agent-browser\` installed globally. It controls a real Chromium browser on display \`:99\` (visible in the user's VNC panel).

**Always use \`--headed\` flag** so the browser renders on the VNC display:

\`\`\`bash
agent-browser --headed <command>
\`\`\`

## Core Workflow

1. **Open a URL**: \`agent-browser --headed open <url>\`
2. **Take a snapshot** to see page structure: \`agent-browser --headed snapshot -i -c\`
3. **Interact** using element refs from the snapshot: \`agent-browser --headed click @e3\`
4. **Verify visually**: Use the \`browser_screenshot\` tool to capture the VNC display and show it in chat.

## Navigation

\`\`\`bash
agent-browser --headed open <url>          # Navigate to URL
agent-browser --headed back                # Go back
agent-browser --headed forward             # Go forward
agent-browser --headed reload              # Reload page
agent-browser --headed close               # Close browser
\`\`\`

## Clicking & Focus

\`\`\`bash
agent-browser --headed click <selector>    # Click element (CSS selector or @ref)
agent-browser --headed dblclick <selector> # Double-click
agent-browser --headed focus <selector>    # Focus element
agent-browser --headed hover <selector>    # Hover over element
\`\`\`

## Text Input

\`\`\`bash
agent-browser --headed type <selector> <text>   # Type into element (appends)
agent-browser --headed fill <selector> <text>    # Clear field and fill with text
agent-browser --headed press <key>               # Press key (Enter, Tab, Control+a, etc.)
\`\`\`

## Form Controls

\`\`\`bash
agent-browser --headed select <selector> <value> # Select dropdown option
agent-browser --headed check <selector>           # Check checkbox
agent-browser --headed uncheck <selector>         # Uncheck checkbox
agent-browser --headed upload <selector> <files>  # Upload files
\`\`\`

## Scrolling

\`\`\`bash
agent-browser --headed scroll down [px]           # Scroll down (default ~page)
agent-browser --headed scroll up [px]             # Scroll up
agent-browser --headed scrollintoview <selector>  # Scroll element into view
\`\`\`

## Snapshots (Accessibility Tree)

Snapshots give you a structured view of the page with element refs (\`@e1\`, \`@e2\`, etc.) you can use in subsequent commands.

\`\`\`bash
agent-browser --headed snapshot              # Full accessibility tree
agent-browser --headed snapshot -i           # Interactive elements only
agent-browser --headed snapshot -c           # Compact output
agent-browser --headed snapshot -i -c        # Interactive + compact (recommended)
agent-browser --headed snapshot -d 3         # Limit depth to 3
agent-browser --headed snapshot -s "main"    # Scope to a CSS selector
\`\`\`

After a snapshot, use the \`@ref\` identifiers to interact:

\`\`\`bash
agent-browser --headed click @e3
agent-browser --headed fill @e7 "search query"
\`\`\`

## Getting Page Information

\`\`\`bash
agent-browser --headed get title             # Page title
agent-browser --headed get url               # Current URL
agent-browser --headed get text <selector>   # Text content of element
agent-browser --headed get html <selector>   # innerHTML of element
agent-browser --headed get value <selector>  # Input value
agent-browser --headed get attr <sel> <attr> # Element attribute
agent-browser --headed get count <selector>  # Count matching elements
\`\`\`

## Checking Element State

\`\`\`bash
agent-browser --headed is visible <selector>  # Check visibility
agent-browser --headed is enabled <selector>  # Check if enabled
agent-browser --headed is checked <selector>  # Check if checked
\`\`\`

## Waiting

\`\`\`bash
agent-browser --headed wait <selector>         # Wait for element to appear
agent-browser --headed wait 2000               # Wait 2 seconds
agent-browser --headed wait --text "Success"   # Wait for text to appear
agent-browser --headed wait --url "**/dashboard" # Wait for URL pattern
\`\`\`

**NEVER use \`wait --load networkidle\`** — many sites never reach network idle (analytics, websockets, polling). It will hang indefinitely and can break the session.

## Semantic Finding

Find elements by role, text, label, etc. and perform actions:

\`\`\`bash
agent-browser --headed find role button click              # Click first button
agent-browser --headed find text "Submit" click            # Click element with text
agent-browser --headed find label "Email" fill "a@b.com"   # Fill by label
agent-browser --headed find placeholder "Search" fill "q"  # Fill by placeholder
agent-browser --headed find testid "login-btn" click       # Click by data-testid
\`\`\`

## Tabs

\`\`\`bash
agent-browser --headed tab                   # List open tabs
agent-browser --headed tab new [url]         # Open new tab
agent-browser --headed tab 2                 # Switch to tab 2
agent-browser --headed tab close [n]         # Close tab
\`\`\`

## JavaScript Evaluation

\`\`\`bash
agent-browser --headed eval "document.title"
agent-browser --headed eval "window.scrollTo(0, document.body.scrollHeight)"
\`\`\`

## Dialogs

\`\`\`bash
agent-browser --headed dialog accept [text]  # Accept alert/confirm/prompt
agent-browser --headed dialog dismiss        # Dismiss dialog
\`\`\`

## Cookies & Storage

\`\`\`bash
agent-browser --headed cookies               # List cookies
agent-browser --headed cookies clear         # Clear cookies
agent-browser --headed storage local         # List localStorage
agent-browser --headed storage local <key>   # Get specific key
\`\`\`

## Common Workflow Examples

### Navigate and extract content

\`\`\`bash
timeout 15 agent-browser --headed open "https://example.com"
agent-browser --headed snapshot -i -c
agent-browser --headed get title
\`\`\`

### Fill a form

\`\`\`bash
timeout 15 agent-browser --headed open "https://example.com/login"
agent-browser --headed snapshot -i -c
timeout 10 agent-browser --headed fill @e3 "user@example.com"
timeout 10 agent-browser --headed fill @e5 "password123"
timeout 15 agent-browser --headed click @e7
agent-browser --headed wait 2000
agent-browser --headed snapshot -i -c
\`\`\`

### Using snapshot refs

\`\`\`bash
agent-browser --headed open "https://news.ycombinator.com"
agent-browser --headed snapshot -i -c
# Output shows refs like @e1, @e2, @e3...
agent-browser --headed click @e5    # Click the 5th interactive element
agent-browser --headed get title    # Verify navigation
\`\`\`

## Avoiding Hangs

Browser commands can hang if a page never finishes loading or a click triggers an unexpected navigation. **Always wrap browser commands with \`timeout\`** to prevent blocking the session:

\`\`\`bash
timeout 15 agent-browser --headed click @e3
timeout 15 agent-browser --headed open "https://example.com"
timeout 15 agent-browser --headed fill @e7 "text"
\`\`\`

Use \`timeout 15\` (15 seconds) as a sensible default. If a command times out, take a snapshot to see what happened and adjust your approach.

**Never use \`wait --load networkidle\`** — it hangs on most real-world sites. Instead, wait for specific elements:

\`\`\`bash
timeout 10 agent-browser --headed wait "input[name=email]"  # Wait for a specific element
timeout 10 agent-browser --headed wait --text "Welcome"     # Wait for specific text
\`\`\`

## Tips

- **Always take a screenshot** with \`browser_screenshot\` after navigating or clicking so you and the user can see the result.
- Use \`snapshot -i -c\` as your go-to for understanding page structure.
- Prefer \`fill\` over \`type\` for form fields (it clears first).
- The browser persists between commands within a session. No need to reopen it.
- If the browser isn't running, \`agent-browser --headed open <url>\` will start it.
`, sortOrder: 0 },
    ],
  },
  {
    name: "cloudflare",
    version: "0.0.1",
    description: "Cloudflare integration for DNS, zones, and workers",
    icon: "☁️",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "deepwiki",
    version: "0.0.1",
    description: "DeepWiki integration for repository knowledge base",
    icon: "📚",
    authRequired: false,
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "email-auth",
    version: "0.1.0",
    description: "Email/password identity provider",
    icon: "key",
    capabilities: [],
    artifacts: [],
  },
  {
    name: "github",
    version: "0.0.1",
    description: "GitHub integration for PRs, issues, repos, and webhooks",
    icon: "🐙",
    capabilities: ["actions","skills"],
    artifacts: [
      { type: "skill", filename: "github.md", content: `---
name: github
description: How to use GitHub integration tools — list repos, create PRs, manage issues, read files. Covers credential routing (personal vs org), available actions, and common patterns.
---

# GitHub Integration Tools

You interact with GitHub through integration actions, NOT the \`gh\` CLI (which is not available in sandboxes).

## Quick Start

\`\`\`
list_tools service=github    # Discover available GitHub actions
call_tool github:github.<action_id> params={...} summary="..."
\`\`\`

## Credential Routing

GitHub tools support two credential sources:

- **\`source=personal\`** — your personal OAuth token. Access to your own repos (public + private).
- **\`source=org\`** — org GitHub App install token. Access to repos in organizations where the App is installed.

Every GitHub action accepts an optional \`source\` parameter. If omitted, the system auto-resolves:
1. If the action has an \`owner\` param matching an org the App covers, uses org credential
2. Otherwise: org credential preferred, personal fallback
3. On auth failure, automatically retries with the other credential

**When to specify \`source\` explicitly:**
- \`list_repos source=personal\` — list your personal repos
- \`list_repos source=org\` — list org-accessible repos
- For repo-specific actions (get_repository, create_pull_request, etc.), auto-resolution usually works — just pass \`owner\` and \`repo\`

## Available Actions

### Repository
- \`github.list_repos\` — list repositories (use \`source\` to choose personal vs org)
- \`github.get_repository\` — get repo details by owner/name
- \`github.create_repository\` — create a new repository
- \`github.fork_repository\` — fork a repository
- \`github.read_repo_file\` — read a file from a repository

### Issues
- \`github.list_issues\` — list issues for a repo
- \`github.get_issue\` — get a specific issue by number
- \`github.create_issue\` — create a new issue
- \`github.update_issue\` — update an issue (title, body, state, labels)

### Pull Requests
- \`github.list_pull_requests\` — list PRs for a repo
- \`github.get_pull_request\` — get a specific PR by number
- \`github.inspect_pull_request\` — get detailed PR info (files, comments, check runs)
- \`github.create_pull_request\` — create a new PR
- \`github.update_pull_request\` — update a PR (title, body, state, labels)
- \`github.merge_pull_request\` — merge a PR
- \`github.create_comment\` — comment on an issue or PR

### Branches & Commits
- \`github.create_branch\` — create a branch from a ref
- \`github.delete_branch\` — delete a branch
- \`github.list_commits\` — list commits on a branch

### Search
- \`github.search_code\` — search code across repositories
- \`github.search_issues\` — search issues and PRs

### Releases & CI
- \`github.create_release\` — create a release with tag
- \`github.list_workflow_runs\` — list GitHub Actions workflow runs

## Common Patterns

### Create a PR after committing changes
\`\`\`
# Use git CLI for local operations
git checkout -b feature/my-change
# ... make changes, commit ...
git push -u origin feature/my-change

# Use integration tool for PR creation (not gh CLI)
call_tool github:github.create_pull_request \\
  owner=<owner> repo=<repo> \\
  title="My change" body="Description" \\
  head="feature/my-change" base="main" \\
  summary="Create PR for feature/my-change"
\`\`\`

### List all repos you have access to
\`\`\`
# Personal repos
call_tool github:github.list_repos source=personal summary="List personal repos"

# Org repos (via GitHub App)
call_tool github:github.list_repos source=org summary="List org repos"
\`\`\`

### Read a file without cloning
\`\`\`
call_tool github:github.read_repo_file \\
  owner=<owner> repo=<repo> path="README.md" \\
  summary="Read README from owner/repo"
\`\`\`

## Important Notes

- The \`gh\` CLI is NOT available. Always use \`call_tool\` with GitHub actions.
- Use git CLI for local operations (checkout, add, commit, push, pull).
- Use \`report_git_state\` after checking out branches or making commits.
- The \`summary\` parameter on \`call_tool\` is required for medium/high risk actions (like creating PRs). Make it descriptive.
`, sortOrder: 0 },
    ],
  },
  {
    name: "gmail",
    version: "0.0.1",
    description: "Gmail integration for reading and sending emails",
    icon: "📧",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "google-auth",
    version: "0.1.0",
    description: "Google OAuth identity provider",
    icon: "google",
    capabilities: [],
    artifacts: [],
  },
  {
    name: "google-calendar",
    version: "0.0.1",
    description: "Google Calendar integration for events and scheduling",
    icon: "📅",
    capabilities: ["actions","skills"],
    artifacts: [
      { type: "skill", filename: "google-calendar.md", content: `---
name: google-calendar
description: How to use Google Calendar tools effectively — managing events, checking availability, scheduling, and working with multiple calendars.
---

# Google Calendar

You have full access to Google Calendar through the \`google-calendar\` plugin.

## Available Tools

### Reading

- **\`calendar.list_calendars\`** — List all calendars the user has access to (with IDs, names, and access roles).
- **\`calendar.get_calendar\`** — Get details for a specific calendar.
- **\`calendar.list_events\`** — List events in a time range. Supports filtering by calendar, time bounds, search text, and single events expansion.
- **\`calendar.get_event\`** — Get full details of a specific event.

### Scheduling

- **\`calendar.create_event\`** — Create an event with title, times, attendees, location, description, and recurrence.
- **\`calendar.update_event\`** — Update any field of an existing event.
- **\`calendar.delete_event\`** — Delete an event.
- **\`calendar.quick_add\`** — Create an event from natural language (e.g., "Lunch with Alice tomorrow at noon").

### Availability

- **\`calendar.respond_to_event\`** — Accept, decline, or tentatively accept an event invitation.
- **\`calendar.query_free_busy\`** — Check busy/free status for one or more people over a time range.
- **\`calendar.find_available_slots\`** — Find open time slots when all specified attendees are available.

## Common Patterns

### Checking Today's Schedule

\`\`\`
calendar.list_events({
  calendarId: "primary",
  timeMin: "2026-03-15T00:00:00Z",
  timeMax: "2026-03-16T00:00:00Z",
  singleEvents: true,
  orderBy: "startTime"
})
\`\`\`

Always use \`singleEvents: true\` and \`orderBy: "startTime"\` when listing a day's events — this expands recurring events and sorts chronologically.

### Scheduling a Meeting

\`\`\`
calendar.create_event({
  calendarId: "primary",
  summary: "Architecture Review",
  start: "2026-03-20T14:00:00-07:00",
  end: "2026-03-20T15:00:00-07:00",
  attendees: ["alice@example.com", "bob@example.com"],
  description: "Review the new API design",
  location: "Conference Room B"
})
\`\`\`

### Finding a Time That Works

Use \`find_available_slots\` to find open times for a group:

\`\`\`
calendar.find_available_slots({
  attendees: ["alice@example.com", "bob@example.com"],
  timeMin: "2026-03-17T09:00:00-07:00",
  timeMax: "2026-03-21T17:00:00-07:00",
  durationMinutes: 30,
  maxResults: 5
})
\`\`\`

### Quick Event Creation

For simple events, \`quick_add\` parses natural language:

\`\`\`
calendar.quick_add({
  calendarId: "primary",
  text: "Team standup every weekday at 9:30am"
})
\`\`\`

### Recurring Events

Use RFC 5545 RRULE format for recurrence:

\`\`\`
calendar.create_event({
  calendarId: "primary",
  summary: "Weekly Sync",
  start: "2026-03-16T10:00:00-07:00",
  end: "2026-03-16T10:30:00-07:00",
  recurrence: ["RRULE:FREQ=WEEKLY;BYDAY=MO;COUNT=12"]
})
\`\`\`

Common RRULE patterns:
- \`RRULE:FREQ=DAILY\` — every day
- \`RRULE:FREQ=WEEKLY;BYDAY=MO,WE,FR\` — Mon/Wed/Fri
- \`RRULE:FREQ=MONTHLY;BYMONTHDAY=1\` — first of each month
- \`RRULE:FREQ=WEEKLY;COUNT=10\` — weekly for 10 occurrences
- \`RRULE:FREQ=WEEKLY;UNTIL=20261231T000000Z\` — weekly until end of year

### All-Day Events

Use date strings (no time component) for all-day events:

\`\`\`
calendar.create_event({
  calendarId: "primary",
  summary: "Company Holiday",
  start: "2026-03-20",
  end: "2026-03-21"
})
\`\`\`

Note: the end date is exclusive — a single all-day event on March 20 uses \`end: "2026-03-21"\`.

## Tips

- **Calendar ID**: Use \`"primary"\` for the user's main calendar. Use \`list_calendars\` to discover other calendar IDs.
- **Timezones**: Always include timezone offsets in datetime strings (e.g., \`-07:00\`). The user's local timezone is preferred.
- **Single events**: When listing, set \`singleEvents: true\` to expand recurring events into individual instances. Without this, you get the recurring event template, not the individual occurrences.
- **Attendees**: Pass email addresses as strings. The API handles sending invitations.
- **Updates**: Only pass the fields you want to change to \`update_event\`. Omitted fields are preserved.
`, sortOrder: 0 },
    ],
  },
  {
    name: "google-docs",
    version: "0.0.1",
    description: "Google Docs integration with markdown-native read/write",
    icon: "📝",
    capabilities: ["actions","skills"],
    artifacts: [
      { type: "skill", filename: "google-docs.md", content: `---
name: google-docs
description: How to use Google Docs tools effectively — markdown formatting, section-based editing, read-before-write patterns, and rich text best practices.
---

# Google Docs

You have full read/write access to Google Docs through the \`google-docs\` plugin. The key advantage is **rich text formatting** — content you write in markdown is automatically converted to properly formatted Google Docs (headings, bold, italic, links, lists, tables, code blocks, etc).

## Critical Rule: Always Use Markdown

**Every piece of content you write to a Google Doc MUST be formatted in markdown.** The system converts markdown to native Google Docs formatting. If you write plain text without markdown, the document will look unformatted and unprofessional.

\`\`\`markdown
# Meeting Notes — March 15, 2026

## Action Items

- **@alice**: Finalize the API spec by Friday
- **@bob**: Review the [design doc](https://docs.google.com/...)
- ~~Cancelled: vendor demo~~ — rescheduled to next week

## Technical Summary

The migration uses a \`three-phase approach\`:

1. **Phase 1** — Schema migration with backwards compatibility
2. **Phase 2** — Dual-write to old and new tables
3. **Phase 3** — Cut over and deprecate old schema
\`\`\`

This produces a document with proper headings, bold names, a clickable link, strikethrough, inline code, and a numbered list — not just raw text.

## Supported Markdown Formatting

| Markdown | Result in Google Docs |
|---|---|
| \`# Heading\` through \`###### Heading\` | Heading 1 through Heading 6 |
| \`**bold**\` | Bold text |
| \`*italic*\` | Italic text |
| \`~~strikethrough~~\` | Strikethrough text |
| \`[text](url)\` | Clickable hyperlink |
| \`\` \`inline code\` \`\` | Monospace font (Roboto Mono, green) |
| Triple-backtick code blocks | Gray-background table cell with monospace font |
| \`- item\` or \`* item\` | Bullet list |
| \`1. item\` | Numbered list |
| \`- [ ] task\` / \`- [x] task\` | Checkbox list items |
| \`---\` | Horizontal rule |
| Markdown tables | Native Google Docs tables |

## Available Tools

### Reading

- **\`docs.search_documents\`** — Find documents by title keyword. Use this to locate documents before reading/editing.
- **\`docs.get_document\`** — Get full document metadata (title, sections, revision info). Good for understanding document structure.
- **\`docs.read_document\`** — Read entire document content as markdown. Tables are annotated as \`[Table N]\` in document order to make \`fillCell\` targeting easier.
- **\`docs.read_section\`** — Read a specific section by heading name. Use for long documents where you only need part of the content.

### Writing (Markdown-Based)

- **\`docs.create_document\`** — Create a new document. Content MUST be markdown.
- **\`docs.replace_document\`** — Replace the entire document body. Content MUST be markdown.
- **\`docs.append_content\`** — Append content to the end of the document. Content MUST be markdown.
- **\`docs.replace_section\`** — Replace the content under a specific heading. Content MUST be markdown.
- **\`docs.insert_section\`** — Insert a new section before or after an existing heading.
- **\`docs.delete_section\`** — Delete a section and all its content.

### Targeted Edits (Format-Preserving)

- **\`docs.update_document\`** — Apply surgical edits with high-level operations. Bypasses markdown conversion entirely, preserving all existing formatting, table styling, and document structure.

**When to use \`update_document\`:**
- Filling in template fields (e.g., replacing \`{{PLACEHOLDER}}\` with values)
- Replacing specific text throughout a document
- Editing individual table cells without destroying cell formatting
- Making small targeted changes to richly formatted documents

**When to use markdown-based tools instead:**
- Rewriting large sections where formatting isn't critical
- Creating new documents from scratch
- Appending new content to the end of a document

**Supported operations:**
- \`replaceAll\` — Find-and-replace across the document. Best for placeholders like \`{{CAPABILITY_NAME}}\`.
- \`fillCell\` — Replace the content of a specific table cell by \`(tableIndex, row, col)\`, using 0-based indexing.
- \`insertText\` — Insert text immediately after an anchor string that already exists in the document.

**Input formats:**
- \`operationsJson\` — Preferred when possible. Pass a normal JSON array of operations, not a JSON string.
- \`operationsToon\` — Supported for token-efficient prompts, but easier to misformat than JSON.

**Document identifiers:**
- All tools that take \`documentId\` accept either a bare document ID or a full Google Docs URL. You do not need to manually strip the ID out of a standard Docs URL.

**Use \`replaceAll\` for placeholders:**
\`\`\`text
documentId: 1Jmzvis-SH_...
operationsJson:
  - type: replaceAll
    find: "{{PROJECT_NAME}}"
    replace: Wallet Export v2
  - type: replaceAll
    find: "{{LAUNCH_DATE}}"
    replace: 2026-04-15
\`\`\`

**Use \`fillCell\` for template tables:**
\`\`\`text
documentId: 1Jmzvis-SH_...
operationsJson:
  - type: fillCell
    tableIndex: 0
    row: 0
    col: 1
    text: Wallet Export v2
  - type: fillCell
    tableIndex: 0
    row: 1
    col: 1
    text: Tier 1
\`\`\`

**Use \`insertText\` for anchored insertions:**
\`\`\`text
documentId: 1Jmzvis-SH_...
operationsJson:
  - type: insertText
    after: "Marketing Owner:"
    text: " Jane Smith"
\`\`\`

\`insertText\` is anchor-based only. It does not accept a raw document index. If you need to insert near existing content, first read the document and choose a stable \`after\` anchor string that already exists.

For \`update_document\`, first read the doc with \`docs.read_document\` to understand the structure:
- Use the \`[Table N]\` labels in the readback to map table indices
- Count table rows and columns starting from \`0\`
- Prefer \`replaceAll\` when the template already has stable placeholder text
- Use \`fillCell\` when a value belongs in a specific table cell
- Use \`insertText\` when you know the exact anchor string already present in the doc
- Prefer \`operationsJson\` unless you specifically need TOON

**Caution:** \`fillCell\` and \`insertText\` require non-empty \`text\`. The Google Docs API rejects empty \`insertText\` requests. If a cell should remain blank, omit the operation for that cell instead of passing an empty string.

**TOON encoding rules:**
- Each TOON block must use a single consistent column schema.
- Do not mix \`replaceAll\`, \`fillCell\`, and \`insertText\` rows in the same TOON block because they have different fields.
- In practice, prefer \`operationsJson\` when mixing operation types.
- If you must use TOON, keep each \`update_document\` call to one operation shape or make separate \`update_document\` calls per shape.

## Common Patterns

### Read Before Write

Always read a document before modifying it to understand its structure:

\`\`\`
1. docs.search_documents({ query: "Q1 Planning" })
2. docs.get_document({ documentId: "..." })      // see section headings
3. docs.read_section({ documentId: "...", sectionHeading: "Budget" })
4. docs.replace_section({ documentId: "...", sectionHeading: "Budget", content: "..." })
\`\`\`

For targeted edits to formatted templates:

\`\`\`
1. docs.read_document({ documentId: "..." })
2. Use the [Table N] labels to identify the table you want, then count row/col positions
3. docs.update_document({
     documentId: "...",
     operationsJson: [
       { type: "replaceAll", find: "{{PROJECT_NAME}}", replace: "Wallet Export v2" },
       { type: "fillCell", tableIndex: 0, row: 2, col: 1, text: "2026-04-01" }
     ]
   })
\`\`\`

### Worked Example: Read → Plan → Fill

Use this workflow when filling a structured template without disturbing formatting:

\`\`\`text
1. docs.read_document({
     documentId: "https://docs.google.com/document/d/1Jmzvis-SH_.../edit"
   })

2. Inspect the markdown response:
   - Find \`[Table 0]\`, \`[Table 1]\`, etc.
   - Note which table row/col holds each value you need to fill
   - Leave untouched cells out of the plan entirely

3. Build the operation list:
   operationsJson:
     - type: replaceAll
       find: "{{CAPABILITY_NAME}}"
       replace: Wallet Export v2
     - type: insertText
       after: "Marketing Owner:"
       text: " Jane Smith"
     - type: fillCell
       tableIndex: 0
       row: 0
       col: 1
       text: Wallet Export v2
     - type: fillCell
       tableIndex: 0
       row: 1
       col: 1
       text: Tier 1

4. Apply the targeted edit:
   docs.update_document({
     documentId: "https://docs.google.com/document/d/1Jmzvis-SH_.../edit",
     operationsJson: [...]
   })

5. Re-read the document and verify the filled cells and inline fields landed in the expected places.
\`\`\`

### Section-Based Editing

Documents are organized by headings. Use section tools to surgically edit specific parts without touching the rest:

- **Replace a section**: \`docs.replace_section\` replaces everything under a heading (up to the next heading of equal or higher level)
- **Insert a section**: \`docs.insert_section\` adds a new section before or after an existing one
- **Delete a section**: \`docs.delete_section\` removes a heading and everything under it

When targeting a section, the heading parameter is a case-insensitive substring match.

### Creating Well-Structured Documents

When creating new documents, use heading hierarchy to establish clear structure:

\`\`\`markdown
# Project Title

Brief overview paragraph.

## Background

Context and motivation.

## Requirements

### Functional Requirements

- Requirement 1
- Requirement 2

### Non-Functional Requirements

- Performance: < 200ms p99
- Availability: 99.9%

## Timeline

| Phase | Date | Milestone |
|---|---|---|
| Design | Mar 20 | Design doc approved |
| Build | Apr 10 | MVP complete |
| Launch | Apr 30 | GA release |
\`\`\`

### Appending to Existing Documents

Use \`docs.append_content\` to add new content at the end. This is useful for running logs, meeting notes, or adding new sections to an existing document.

### Code in Documents

Code blocks render as gray-background table cells with monospace font, making them visually distinct:

\`\`\`\`markdown
\`\`\`python
def hello():
    print("Hello, world!")
\`\`\`
\`\`\`\`

Inline code like \`variable_name\` renders in green monospace font.

## Tips

- **Search first**: Use \`docs.search_documents\` to find documents by title before working with them. You need the document ID for all other operations.
- **Use sections**: For large documents, prefer \`read_section\` and \`replace_section\` over reading/replacing the entire document.
- **Markdown everywhere**: Every content string — in create, replace, append, insert — is parsed as markdown. Take advantage of this for professional-looking documents.
- **Targeted edits are not markdown**: \`docs.update_document\` writes plain text into existing structures and takes either \`operationsJson\` or a TOON-encoded operation list. Use it when preserving current formatting matters more than generating new formatting from markdown.
- **Heading levels matter**: Section operations use heading hierarchy. A \`## Subheading\` under \`# Heading\` is part of the \`# Heading\` section. Replacing \`# Heading\` replaces everything including sub-sections.
`, sortOrder: 0 },
    ],
  },
  {
    name: "google-drive",
    version: "0.0.1",
    description: "Google Drive integration for files and documents",
    icon: "📁",
    capabilities: ["actions","skills"],
    artifacts: [
      { type: "skill", filename: "google-drive.md", content: `---
name: google-drive
description: How to use Google Drive tools effectively — file search, reading, creating, organizing, sharing, and working with Google Workspace file types.
---

# Google Drive

You have full access to Google Drive through the \`google-drive\` plugin. Drive is the file system — use it to find, read, create, organize, and share files. For editing Google Docs or Sheets content, use the dedicated \`google-docs\` or \`google-sheets\` tools instead.

## Available Tools

### Finding Files

- **\`drive.list_files\`** — List files in a folder (or root). Supports query filters, MIME type filtering, sorting, and pagination.
- **\`drive.search_files\`** — Full-text search across file names and content. The fastest way to find a file.
- **\`drive.get_file\`** — Get full metadata for a file by ID (name, type, size, owners, sharing status, links).

### Reading Content

- **\`drive.read_file\`** — Read text content of a file. Automatically exports Google Workspace files (Docs → plain text, Sheets → CSV). Extracts text from PDFs. Rejects binary files.
- **\`drive.export_file\`** — Export a Google Workspace file to a specific text format (plain text, CSV, HTML, JSON, XML).

### Creating & Updating

- **\`drive.create_file\`** — Create a new file with text content. Set \`mimeType\` to a Google Apps type to create native Workspace files.
- **\`drive.create_folder\`** — Create a new folder.
- **\`drive.update_content\`** — Replace the content of an existing file.
- **\`drive.update_metadata\`** — Rename, move, star, or update description of a file.
- **\`drive.copy_file\`** — Copy a file, optionally to a different folder with a new name.

### Sharing

- **\`drive.share_file\`** — Share with a user, group, domain, or anyone. Set role (reader/commenter/writer/organizer).
- **\`drive.list_permissions\`** — List all permissions on a file.
- **\`drive.remove_permission\`** — Remove a specific permission.

### Cleanup

- **\`drive.trash_file\`** — Move to trash (recoverable).
- **\`drive.untrash_file\`** — Restore from trash.
- **\`drive.delete_file\`** — Permanently delete (cannot be undone).

## Common Patterns

### Finding a File

Search is the fastest way to find files:

\`\`\`
drive.search_files({ query: "Q1 budget report" })
\`\`\`

To browse a specific folder:

\`\`\`
drive.list_files({ folderId: "folder-id-here", orderBy: "modifiedTime desc" })
\`\`\`

To find files by type:

\`\`\`
drive.list_files({ mimeType: "application/vnd.google-apps.spreadsheet" })
\`\`\`

### Reading Google Workspace Files

\`read_file\` auto-exports Workspace files to readable text:

- Google Docs → plain text
- Google Sheets → CSV
- Google Slides → plain text

For more control over the export format, use \`export_file\`:

\`\`\`
drive.export_file({ fileId: "...", mimeType: "text/html" })        // Docs as HTML
drive.export_file({ fileId: "...", mimeType: "text/csv" })          // Sheets as CSV
drive.export_file({ fileId: "...", mimeType: "text/plain" })        // Slides as text
\`\`\`

### Creating a Google Doc via Drive

To create a native Google Doc (not a plain text file), set the Google Apps MIME type:

\`\`\`
drive.create_file({
  name: "Meeting Notes",
  content: "# Meeting Notes\\n\\nAgenda items...",
  mimeType: "application/vnd.google-apps.document",
  folderId: "folder-id-here"
})
\`\`\`

The content is uploaded as plain text and converted to a native Google Doc. For rich formatting, use \`google-docs\` tools instead — they support full markdown-to-Docs conversion.

### Organizing Files

Move a file to a different folder:

\`\`\`
drive.update_metadata({
  fileId: "...",
  addParents: "target-folder-id",
  removeParents: "current-folder-id"
})
\`\`\`

Rename a file:

\`\`\`
drive.update_metadata({ fileId: "...", name: "New Name" })
\`\`\`

### Sharing Files

Share with a specific person:

\`\`\`
drive.share_file({
  fileId: "...",
  role: "writer",
  type: "user",
  emailAddress: "alice@example.com"
})
\`\`\`

Share with anyone who has the link:

\`\`\`
drive.share_file({
  fileId: "...",
  role: "reader",
  type: "anyone"
})
\`\`\`

## Google Workspace MIME Types

| Type | MIME Type |
|---|---|
| Google Docs | \`application/vnd.google-apps.document\` |
| Google Sheets | \`application/vnd.google-apps.spreadsheet\` |
| Google Slides | \`application/vnd.google-apps.presentation\` |
| Google Forms | \`application/vnd.google-apps.form\` |
| Google Drawings | \`application/vnd.google-apps.drawing\` |
| Folder | \`application/vnd.google-apps.folder\` |

## When to Use Drive vs Dedicated Plugins

Drive is the file system layer — use it for finding, organizing, and sharing files. For reading or editing the **content** of Google Workspace files, always use the dedicated plugin:

| Task | Use This | NOT This |
|------|----------|----------|
| Create a Google Sheet | \`sheets.create_spreadsheet\` | \`drive.create_file\` with spreadsheet MIME type |
| Read spreadsheet data | \`sheets.read_range\` | \`drive.read_file\` (exports as CSV, loses structure) |
| Write/format cells | \`sheets.write_range\`, \`sheets.format_cells\` | \`drive.update_content\` (replaces whole file) |
| Create a Google Doc | \`docs.create_document\` | \`drive.create_file\` with document MIME type |
| Edit document sections | \`docs.replace_section\` | \`drive.update_content\` (replaces whole file) |
| Read a document | \`docs.read_document\` | \`drive.read_file\` (exports as plain text, loses formatting) |
| Send an email | \`gmail.send_message\` | N/A |
| Create a calendar event | \`calendar.create_event\` | N/A |

**Drive is the right tool for:**
- Searching for files across the user's Drive (\`drive.search_files\`)
- Getting file metadata, URLs, and sharing status (\`drive.get_file\`)
- Moving, renaming, copying, or organizing files (\`drive.update_metadata\`, \`drive.copy_file\`)
- Sharing and permissions (\`drive.share_file\`)
- Creating plain text files or uploading non-Workspace files
- Trashing/deleting files

**Drive is NOT the right tool for:**
- Creating or editing Google Sheets — use \`google-sheets\` tools (they support cell-level reads, writes, formatting, and formulas)
- Creating or editing Google Docs — use \`google-docs\` tools (they support markdown conversion and section-level editing)
- Anything that requires understanding the internal structure of a Workspace file

## Tips

- **Search broadly**: \`search_files\` searches both file names and content. It's the best starting point when looking for something.
- **Read file handles PDFs**: \`read_file\` automatically extracts text from PDF files.
- **Binary files are rejected**: \`read_file\` only works with text-based files, Google Workspace files, and PDFs. Use \`get_file\` for metadata of binary files.
- **Trash before delete**: Prefer \`trash_file\` over \`delete_file\` — trashed files can be recovered.
`, sortOrder: 0 },
    ],
  },
  {
    name: "google-sheets",
    version: "0.0.1",
    description: "Google Sheets integration for spreadsheet operations",
    icon: "📊",
    capabilities: ["actions","skills"],
    artifacts: [
      { type: "skill", filename: "google-sheets.md", content: `---
name: google-sheets
description: How to use Google Sheets tools effectively — reading/writing ranges, A1 notation, multi-range reads, spreadsheet structure, and common data patterns.
---

# Google Sheets

You have full read/write access to Google Sheets through the \`google-sheets\` plugin.

## Available Tools

### Reading

- **\`sheets.get_spreadsheet\`** — Get spreadsheet metadata: title, sheet names, grid dimensions. Always start here to understand the spreadsheet structure.
- **\`sheets.read_range\`** — Read a single range of cells (returns 2D array of values).
- **\`sheets.read_multiple_ranges\`** — Read multiple ranges in one call (more efficient than multiple single reads).

### Writing

- **\`sheets.write_range\`** — Write values to a specific range (overwrites existing data).
- **\`sheets.append_rows\`** — Append rows after the last row with data. Use for adding entries to tables/logs.
- **\`sheets.clear_range\`** — Clear values from a range without deleting cells.

### Spreadsheet Management

- **\`sheets.create_spreadsheet\`** — Create a new spreadsheet with a title and optional sheet names.
- **\`sheets.add_sheet\`** — Add a new sheet (tab) to an existing spreadsheet.
- **\`sheets.delete_sheet\`** — Delete a sheet by its numeric ID (use \`get_spreadsheet\` to find sheet IDs).

### Formatting

- **\`sheets.read_formatting\`** — Read cell formatting (colors, bold, borders, alignment) from a range. Always use this before writing to a styled spreadsheet so you can match existing styles.
- **\`sheets.format_cells\`** — Apply formatting to a range. Use \`format\` for uniform styling across all cells, or \`formats\` for per-cell control. Can also merge/unmerge cells.

**\`sheets.write_range\`** and **\`sheets.append_rows\`** also accept optional \`format\` or \`formats\` parameters to write values and styling in a single call.

**Important:** When using \`format_cells\` or \`write_range\` with formatting, the range must include explicit row numbers (e.g., \`"Sheet1!A1:D10"\`, not \`"Sheet1!A:D"\`). Column-only ranges work for value-only operations and \`append_rows\`, but formatting actions need exact cell boundaries.

## A1 Notation

All range parameters use A1 notation:

| Notation | Meaning |
|---|---|
| \`Sheet1!A1:C10\` | Cells A1 through C10 on Sheet1 |
| \`Sheet1!A:C\` | Entire columns A through C |
| \`Sheet1!1:5\` | Entire rows 1 through 5 |
| \`A1:C10\` | Range on the first sheet (omitting sheet name) |
| \`Sheet1!A1\` | Single cell |
| \`'Sheet Name With Spaces'!A1:B2\` | Quote sheet names with spaces |

## Common Patterns

### Understand Before Modifying

Always check the spreadsheet structure first:

\`\`\`
1. sheets.get_spreadsheet({ spreadsheetId: "..." })     // see sheet names, dimensions
2. sheets.read_range({ spreadsheetId: "...", range: "Sheet1!A1:Z1" })  // read headers
3. sheets.read_range({ spreadsheetId: "...", range: "Sheet1!A1:Z10" }) // read sample data
4. sheets.write_range({ ... })  // now write with confidence
\`\`\`

### Reading a Full Table

Read the header row first to understand columns, then read the data:

\`\`\`
1. sheets.read_range({ range: "Sheet1!1:1" })           // headers
2. sheets.read_range({ range: "Sheet1!A2:Z" })          // all data rows
\`\`\`

Or read everything at once:

\`\`\`
sheets.read_range({ range: "Sheet1!A1:Z" })
\`\`\`

### Multi-Range Reads

When you need data from different parts of a spreadsheet, use a single \`read_multiple_ranges\` call:

\`\`\`
sheets.read_multiple_ranges({
  spreadsheetId: "...",
  ranges: ["Sheet1!A1:D10", "Summary!A1:B5", "Sheet1!F1:F10"]
})
\`\`\`

### Appending Data

Use \`append_rows\` to add new rows to the end of a table. The range should cover the table area — Sheets finds the last row automatically:

\`\`\`
sheets.append_rows({
  spreadsheetId: "...",
  range: "Sheet1!A:D",
  values: [
    ["2026-03-15", "New item", 42, "active"],
    ["2026-03-15", "Another item", 17, "pending"]
  ]
})
\`\`\`

### Writing Data

Values are always a 2D array (rows of cells):

\`\`\`
sheets.write_range({
  spreadsheetId: "...",
  range: "Sheet1!A1:C3",
  values: [
    ["Name", "Score", "Status"],
    ["Alice", 95, "Pass"],
    ["Bob", 82, "Pass"]
  ]
})
\`\`\`

### Creating a New Spreadsheet

\`\`\`
sheets.create_spreadsheet({
  title: "Q1 2026 Budget",
  sheetTitles: ["Overview", "Monthly", "Categories"]
})
\`\`\`

## Tips

- **Check structure first**: Always call \`get_spreadsheet\` before writing to understand the sheet names and dimensions.
- **Use \`read_multiple_ranges\`** when you need data from several places — it's one API call instead of many.
- **Append vs Write**: Use \`append_rows\` to add to the end of a table. Use \`write_range\` to overwrite a specific location.
- **Empty cells**: Empty cells appear as empty strings \`""\` in read results. When writing, use \`""\` or \`null\` for empty cells.
- **Sheet IDs vs Names**: Most tools use sheet names in A1 notation. \`delete_sheet\` uses numeric sheet IDs (found in \`get_spreadsheet\` metadata).

## Formatting

### Preserving Existing Styles

When editing a spreadsheet that already has styling, always match the existing formatting:

1. Read formatting from a reference row (usually the row above where you're inserting, or a representative data row):
   \`\`\`
   sheets.read_formatting({ spreadsheetId: "...", range: "Sheet1!A5:F5" })
   \`\`\`

2. If all columns share the same style, pass it as a uniform format:
   \`\`\`
   sheets.append_rows({
     spreadsheetId: "...",
     range: "Sheet1!A:F",
     values: [["New item", "Description", ...]],
     format: <format from step 1's formats[0][0]>
   })
   \`\`\`

3. If columns have different styles (e.g., column A is bold, column C has a color), use per-cell formatting to preserve column-specific styles:
   \`\`\`
   sheets.append_rows({
     spreadsheetId: "...",
     range: "Sheet1!A:F",
     values: [["New item", "Description", ...]],
     formats: [<formats[0] from step 1>]
   })
   \`\`\`

**Working with \`read_formatting\` results:**

The response has shape \`{ range, formats: CellFormat[][], merges: Merge[] }\`. The \`formats\` field is a 2D grid (rows × columns). To use it:

- **Uniform style** (all columns same): pass \`result.data.formats[0][0]\` to the \`format\` parameter
- **Per-column style** (different columns have different formatting): pass \`[result.data.formats[0]]\` to the \`formats\` parameter — note the wrapping array, since \`formats\` expects \`CellFormat[][]\`

Do NOT pass the full response object to \`format\` or \`formats\` — you must index into the \`formats\` grid first.

**Key rule:** When appending to a table, copy the format from the last data row — not the header or a section divider.

### Color Reference

Colors use RGB floats from 0 to 1. Common values:

| Color | Value |
|-------|-------|
| White | \`{ red: 1, green: 1, blue: 1 }\` |
| Black | \`{ red: 0, green: 0, blue: 0 }\` |
| Light gray (subtle bg) | \`{ red: 0.95, green: 0.95, blue: 0.95 }\` |
| Medium gray (borders) | \`{ red: 0.7, green: 0.7, blue: 0.7 }\` |
| Dark gray (header bg) | \`{ red: 0.2, green: 0.2, blue: 0.2 }\` |
| Light green | \`{ red: 0.85, green: 0.95, blue: 0.85 }\` |
| Light blue | \`{ red: 0.85, green: 0.92, blue: 1 }\` |
| Light yellow | \`{ red: 1, green: 0.97, blue: 0.85 }\` |
| Red (error/alert) | \`{ red: 0.9, green: 0.2, blue: 0.2 }\` |
| Green (success) | \`{ red: 0.2, green: 0.66, blue: 0.33 }\` |
| Blue (links/accent) | \`{ red: 0.16, green: 0.38, blue: 0.71 }\` |
| White text | \`foregroundColor: { red: 1, green: 1, blue: 1 }\` |

### Creating Well-Formatted Spreadsheets

**Professional header row:**
\`\`\`
sheets.write_range({
  spreadsheetId: "...",
  range: "Sheet1!A1:D1",
  values: [["Name", "Role", "Status", "Score"]],
  format: {
    backgroundColor: { red: 0.2, green: 0.2, blue: 0.2 },
    textFormat: {
      bold: true,
      foregroundColor: { red: 1, green: 1, blue: 1 },
      fontSize: 11
    },
    horizontalAlignment: "LEFT",
    borders: {
      bottom: { style: "SOLID_MEDIUM", color: { red: 0.4, green: 0.4, blue: 0.4 } }
    }
  }
})
\`\`\`

**Section divider row** (dark background spanning all columns):
\`\`\`
sheets.write_range({
  spreadsheetId: "...",
  range: "Sheet1!A10:D10",
  values: [["SECTION TITLE", "", "", ""]],
  format: {
    backgroundColor: { red: 0.25, green: 0.3, blue: 0.2 },
    textFormat: {
      bold: true,
      foregroundColor: { red: 1, green: 1, blue: 1 },
      fontSize: 11
    }
  }
})
\`\`\`

**Alternating row colors** for readability:
\`\`\`
// After writing data rows, apply striped background:
// Odd rows (1, 3, 5...): light gray
sheets.format_cells({
  spreadsheetId: "...",
  range: "Sheet1!A2:D2",
  format: { backgroundColor: { red: 0.95, green: 0.95, blue: 0.95 } }
})
// Even rows (2, 4, 6...): white (or skip — white is default)
\`\`\`

**Standard data table recipe:**
1. Write header row with formatting (bold, dark bg, white text, bottom border)
2. Write data rows with \`write_range\` (values only or with per-row alternating colors)
3. Optionally apply a bottom border on the last data row to close the table

### Formatting Properties Reference

**CellFormat fields:**

| Property | Type | Example |
|----------|------|---------|
| \`backgroundColor\` | Color | \`{ red: 0.95, green: 0.95, blue: 0.95 }\` |
| \`textFormat.bold\` | boolean | \`true\` |
| \`textFormat.italic\` | boolean | \`true\` |
| \`textFormat.strikethrough\` | boolean | \`true\` |
| \`textFormat.underline\` | boolean | \`true\` |
| \`textFormat.fontSize\` | number | \`12\` |
| \`textFormat.fontFamily\` | string | \`"Arial"\` |
| \`textFormat.foregroundColor\` | Color | \`{ red: 0, green: 0, blue: 0 }\` |
| \`horizontalAlignment\` | enum | \`"LEFT"\`, \`"CENTER"\`, \`"RIGHT"\` |
| \`verticalAlignment\` | enum | \`"TOP"\`, \`"MIDDLE"\`, \`"BOTTOM"\` |
| \`wrapStrategy\` | enum | \`"OVERFLOW_CELL"\`, \`"CLIP"\`, \`"WRAP"\` |
| \`numberFormat.type\` | enum | \`"NUMBER"\`, \`"CURRENCY"\`, \`"PERCENT"\`, \`"DATE"\` |
| \`numberFormat.pattern\` | string | \`"#,##0.00"\`, \`"yyyy-mm-dd"\` |
| \`borders.top\` | Border | \`{ style: "SOLID", color: { red: 0 } }\` |
| \`borders.bottom\` | Border | \`{ style: "SOLID_MEDIUM" }\` |
| \`borders.left\` | Border | \`{ style: "DASHED" }\` |
| \`borders.right\` | Border | \`{ style: "DOUBLE" }\` |

**Border styles:** \`NONE\`, \`SOLID\`, \`SOLID_MEDIUM\`, \`SOLID_THICK\`, \`DASHED\`, \`DOTTED\`, \`DOUBLE\`

### Merge Coordinates

Merges use 0-based row and column indices (not A1 notation):
- Column A = 0, B = 1, ..., Z = 25, AA = 26
- Row 1 = 0, Row 2 = 1, etc.
- \`endRowIndex\` and \`endColumnIndex\` are exclusive (same as Python slice notation)

Example: merge A1:C1 on the first sheet:
\`\`\`
{ sheetId: 0, startRowIndex: 0, endRowIndex: 1, startColumnIndex: 0, endColumnIndex: 3 }
\`\`\`

### Formatting Best Practices

- **Always read before writing to styled sheets.** Use \`read_formatting\` on a nearby row and pass the result to \`write_range\` or \`append_rows\`.
- **Use \`format\` (uniform) when all cells share the same style.** Use \`formats\` (per-cell) when columns have different formatting.
- **Only set properties you intend to change.** Omitted properties are preserved — you don't need to specify every field.
- **For borders, set one side only.** The cell below doesn't also need a \`top\` border if the cell above has a \`bottom\` border.
- **Use \`write_range\` with formatting for one-call writes.** This avoids a window where data appears without styling.
`, sortOrder: 0 },
    ],
  },
  {
    name: "linear",
    version: "0.0.1",
    description: "Linear integration for issue tracking and project management",
    icon: "🎯",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "memory-compaction",
    version: "0.0.1",
    description: "Memory compaction plugin for OpenCode",
    icon: "🧠",
    capabilities: ["tools"],
    artifacts: [
      { type: "tool", filename: "memory-compaction.ts", content: `export default async () => {
  return {
    "experimental.session.compacting": async (_input: unknown, output: { context: string[] }) => {
      output.context.push(\`
COMPACTION INSTRUCTIONS — follow exactly before writing your summary:

Your summary must contain these sections. Do NOT omit any of them.
Anything not captured here is permanently lost after compaction.

## Active Work
- Task(s) currently in progress (what, status, what's blocking)
- Child session IDs and their last known status
- What the user is waiting for (if anything)

## Key Decisions Made
- Architectural, process, or preference decisions from this session
- Any constraints or bugs discovered

## Artifacts Created
- Branches, PRs, commits, files changed (include identifiers like PR #N, branch name, commit SHA)

## Things to Remember
- Repo URLs learned this session
- User preferences stated this session
- Project facts discovered (stack, conventions, etc.)

## Resume Instructions
When you resume after this compaction, your FIRST action must be:
1. Call mem_patch to write a journal entry summarizing the above:
   mem_patch("journal/YYYY-MM-DD.md", [{ op: "append", content: "\\\\n\\\\n## [time] — Resumed after compaction\\\\n[paste Active Work + Artifacts here]" }])
2. Check on any child sessions that were running (use get_session_status)
3. Then continue whatever was in progress

Do not respond to the user before completing step 1.
\`);
    },
  };
};
`, sortOrder: 0 },
    ],
  },
  {
    name: "notion",
    version: "0.0.1",
    description: "Notion integration for pages, databases, and workspaces",
    icon: "📝",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "personas",
    version: "0.0.1",
    description: "Agent persona and skill management",
    icon: "🎭",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "personas.md", content: `---
name: personas
description: Create and configure agent personas with attached skills. Manage the skill library and understand skill sources.
---

# Persona & Skill Management

## Concepts

### Skills

Skills are markdown documents that teach agents how to perform specific tasks. Every skill has a **source** that determines where it came from and whether you can edit it:

| Source | What it is | Editable? | Example |
|--------|-----------|-----------|---------|
| \`builtin\` | Platform-shipped skills | No | browser, workflows |
| \`plugin\` | Skills from installed extensions | No | custom org plugins |
| \`managed\` | Skills created by users or agents | Yes (owner only) | "deploy-checklist", "code-review-frontend" |

Skills also have **visibility**:
- \`private\` — only the creator can see and use it
- \`shared\` — visible to the entire org

### Personas

Personas are instruction sets that customize agent behavior. A persona has:
- **Name and icon** — human-readable identity
- **Instructions** — system prompt markdown that defines the agent's role and behavior
- **Attached skills** — skills that auto-load when a session starts with this persona

### How skills reach an agent session

When a session starts, the system loads skills in this order:
1. If the session has a **persona** → load skills attached to that persona
2. If no persona → load **org default skills**
3. Agent can always **search and read** additional skills on demand from the full library

This means attaching a skill to a persona guarantees it's in the agent's context from the first message — no searching needed.

## Common Workflows

### Creating a specialized agent

1. **Create skills** for the agent's domain knowledge:
   \`\`\`
   create_skill(name: "Frontend Code Review", content: "# Frontend Review Standards\\n\\n...")
   \`\`\`

2. **Create a persona** with role instructions:
   \`\`\`
   create_persona(name: "Frontend Reviewer", icon: "🔍", instructions: "You are a frontend code reviewer...")
   \`\`\`

3. **Attach skills** to the persona:
   \`\`\`
   attach_skill_to_persona(personaId: "<persona-id>", skillId: "<skill-id>")
   \`\`\`

4. **Spawn a session** with the persona (from orchestrator):
   \`\`\`
   spawn_session(task: "Review PR #42", persona_id: "<persona-id>", ...)
   \`\`\`

### Inspecting a persona's configuration

\`\`\`
list_persona_skills(personaId: "<persona-id>")
\`\`\`

Returns all attached skills with their source, description, and sort order.

### Reusing existing skills

Before creating a new skill, search the library:
\`\`\`
search_skills(query: "code review")
\`\`\`

You can attach builtin or plugin skills to personas — they don't need to be managed. Any skill from any source can be attached.

### Updating a persona's skill set

- **Add a skill:** \`attach_skill_to_persona(personaId, skillId)\`
- **Remove a skill:** \`detach_skill_from_persona(personaId, skillId)\`
- **Reorder:** Re-attach with a different \`sortOrder\` — attaching an already-attached skill updates its sort order (lower = loaded first)

## Tool Reference

| Tool | Purpose |
|------|---------|
| \`create_persona\` | Create a new persona with name, icon, instructions |
| \`update_persona\` | Update persona metadata or instructions |
| \`delete_persona\` | Remove a persona |
| \`list_personas\` | List all available personas |
| \`create_skill\` | Create a managed skill |
| \`update_skill\` | Update a managed skill's content |
| \`delete_skill\` | Delete a managed skill |
| \`search_skills\` | Search the skill library by keyword |
| \`read_skill\` | Read a skill's full content |
| \`attach_skill_to_persona\` | Attach a skill to a persona |
| \`detach_skill_from_persona\` | Detach a skill from a persona |
| \`list_persona_skills\` | List skills attached to a persona |

## Tips

- **Visibility defaults differ:** Skills default to \`private\`, personas default to \`shared\`. Set visibility explicitly when creating.
- **Sort order matters:** Skills load in sort order. Put foundational skills (coding standards, conventions) at lower sort orders so they appear first in context.
- **Managed skills only:** You can only edit/delete skills with \`source: managed\`. Builtin and plugin skills are read-only, but you can still attach them to personas.
- **Skill content format:** Use YAML frontmatter for metadata (tags, version) followed by markdown content. The content is what gets loaded into the agent's context.
`, sortOrder: 0 },
    ],
  },
  {
    name: "sandbox-tunnels",
    version: "0.0.1",
    description: "Sandbox tunnel management",
    icon: "🔗",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "sandbox-tunnels.md", content: `---
name: sandbox-tunnels
description: Expose sandboxed services via public Cloudflare Quick Tunnels. Each tunnel gets a unique hostname with no path prefix — apps work as if hosted at root.
---

# Sandbox Tunnels

## Goal
Expose sandboxed services through public Cloudflare Quick Tunnels. Each tunnel gets its own unique \`*.trycloudflare.com\` hostname — no path prefix, no base URL configuration needed.

## Quick Path
1. Start services bound to \`0.0.0.0\` inside the sandbox.
2. Register tunnels via \`register_tunnel\`.
3. Use the returned public URL directly — no CORS, no base path.

## Tunnel Workflow
1. Start backend:
   - Example: \`python backend.py --host 0.0.0.0 --port 3000\`
2. Start frontend:
   - Example: \`pnpm dev --host 0.0.0.0 --port 3001\`
3. Register tunnels:
   - \`register_tunnel { name: "api", port: 3000 }\`
   - \`register_tunnel { name: "frontend", port: 3001 }\`
4. Each tunnel returns a unique public URL like \`https://random-words.trycloudflare.com\`
5. Share the URL — no token or auth needed for public access.

## Key Differences from Gateway Tunnels
- **No path prefix**: Apps are served at \`/\`, not \`/t/<name>/\`.
- **No base path config**: No need to set \`base\`, \`basePath\`, \`PUBLIC_URL\`, or \`assetPrefix\`.
- **No JWT/token**: Cloudflare Quick Tunnels are publicly accessible (no gateway auth).
- **Independent hostnames**: Each tunnel is a separate origin — no CORS between tunnels.

## Cross-Origin Between Tunnels
Since each tunnel is its own origin, frontend-to-backend calls are cross-origin. Options:
- **Enable CORS** on the backend (recommended for APIs).
- **Proxy through the frontend** (e.g., Vite proxy, Next.js rewrites).
- **Use the gateway fallback**: The old \`/t/<name>\` paths still work through the gateway for same-origin access.

## Frontend Integration
\`\`\`js
// Use the tunnel URL directly
const API_URL = "https://backend-words.trycloudflare.com"
fetch(\`\${API_URL}/health\`)

// Or set via environment variable
// API_URL=https://backend-words.trycloudflare.com
\`\`\`

## WebSocket Support
Cloudflare Quick Tunnels support WebSockets natively:
\`\`\`js
const ws = new WebSocket("wss://backend-words.trycloudflare.com/ws")
\`\`\`

## Debugging Checklist
- \`ss -tlnp | rg <port>\`: confirm service is listening on 0.0.0.0.
- \`curl -sS http://127.0.0.1:<port>/health\`: confirm service responds locally.
- If tunnel URL returns 502, the local service isn't reachable on that port.
- \`list_tunnels\` to see all active tunnels and their URLs.

## Deleting Tunnels
- \`unregister_tunnel { name: "api" }\` kills the cloudflared process.
- Users can also delete tunnels from the session UI.

## Gateway Fallback
The gateway \`/t/<name>\` paths still work for same-origin access within the sandbox. These require JWT auth and are useful for internal service-to-service calls.

## API Access
- \`GET /api/sessions/:id/tunnels\` → \`{ gatewayUrl, tunnels }\` (tunnels include cloudflared URLs)
`, sortOrder: 0 },
    ],
  },
  {
    name: "sentry",
    version: "0.0.1",
    description: "Sentry integration for error tracking and monitoring",
    icon: "🐛",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "slack",
    version: "0.0.1",
    description: "Slack integration for actions (messages, channels, users) and channel transport",
    icon: "💬",
    capabilities: ["actions","channels"],
    artifacts: [],
  },
  {
    name: "stripe",
    version: "0.0.1",
    description: "Stripe integration for payments, customers, and subscriptions",
    icon: "💳",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "telegram",
    version: "0.0.1",
    description: "Telegram bot messaging and transport",
    icon: "📱",
    capabilities: ["channels"],
    artifacts: [],
  },
  {
    name: "typefully",
    version: "0.0.1",
    description: "Typefully integration for social media content management",
    icon: "📝",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "workflows",
    version: "0.0.1",
    description: "Workflow lifecycle and operations",
    icon: "🔄",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "workflows.md", content: `---
name: workflows
description: End-to-end Valet workflow operations. Use when creating, updating, deleting, running, scheduling, debugging, rolling back, or self-modifying workflows; when managing workflow executions and approvals; when configuring trigger behavior; when passing repository context into workflow runs; and when using agent_message workflow steps.
---

# Workflows

## Use the workflow tools, not raw API calls

Use these tools for lifecycle operations:

- \`list_workflows\`, \`get_workflow\`, \`sync_workflow\`, \`update_workflow\`, \`delete_workflow\`
- \`list_workflow_history\`, \`rollback_workflow\`
- \`list_workflow_proposals\`, \`create_workflow_proposal\`, \`review_workflow_proposal\`, \`apply_workflow_proposal\`
- \`run_workflow\`, \`list_workflow_executions\`, \`get_execution\`, \`get_execution_steps\`, \`debug_execution\`, \`approve_execution\`, \`cancel_execution\`
- \`list_triggers\`, \`sync_trigger\`, \`run_trigger\`, \`delete_trigger\`

## Think in 4 layers

1. Workflow definition: versioned JSON with non-empty \`steps\`.
2. Trigger configuration: dispatch rules for \`manual\`, \`webhook\`, or \`schedule\`.
3. Execution record: immutable run state, status, step traces, and approval token lifecycle.
4. Workflow session: dedicated sandbox session (\`purpose: workflow\`) started/woken by the workflow executor.

## Choose the right lifecycle tool

- Use \`sync_workflow\` for create or full-definition upsert.
- Use \`update_workflow\` for partial metadata/definition patch (\`name\`, \`description\`, \`slug\`, \`version\`, \`enabled\`, \`tags\`, \`data\`).
- Use \`delete_workflow\` to remove workflows (and linked triggers).
- Use \`list_workflow_history\` before rollback or forensic comparison.
- Use \`rollback_workflow\` with a \`target_workflow_hash\` from history.

## Use proposal flow for self-modifying workflows

Follow this sequence:

1. Use \`get_workflow\` and compute/use current workflow hash as \`base_workflow_hash\`.
2. Use \`create_workflow_proposal\`.
3. Use \`review_workflow_proposal\` (\`approve=true/false\`).
4. Use \`apply_workflow_proposal\` after approval.

Notes:

- Proposal creation enforces base-hash matching.
- Workflow must allow self-modification (\`constraints.allowSelfModification === true\`).
- Use \`list_workflow_proposals\` to inspect status transitions (\`pending\`, \`approved\`, \`rejected\`, \`applied\`, \`failed\`).

## Run and operate executions

Run:

- Use \`run_workflow\` with \`workflow_id\`.
- Optionally pass \`variables_json\`.
- Optionally pass repo context: \`repo_url\`, \`repo_branch\`, \`repo_ref\`, \`source_repo_full_name\`.

Inspect:

- Use \`list_workflow_executions\` for recent runs.
- Use \`get_execution\` for authoritative status and current \`resumeToken\`.
- Use \`get_execution_steps\` for ordered normalized step traces.
- Use \`debug_execution\` first when a run stalls/fails.

Approval/cancel:

- Use \`approve_execution\` with the latest \`resume_token\` from \`get_execution\`.
- Use \`cancel_execution\` for stuck/inconsistent runs.

## Configure triggers and scheduling

Use \`sync_trigger\` for create/update:

- \`type=manual\`
- \`type=webhook\` requires \`webhook_path\` (optional method/secret)
- \`type=schedule\` requires \`schedule_cron\`

Schedule specifics:

- \`schedule_cron\` must be a 5-field cron expression.
- \`schedule_timezone\` uses IANA TZ names.
- \`schedule_target=workflow\` (default): dispatches workflow execution.
- \`schedule_target=orchestrator\`: dispatches \`schedule_prompt\` to orchestrator session.
- \`schedule_prompt\` is required when \`schedule_target=orchestrator\`.

Use \`run_trigger\` to test behavior immediately.

Use \`delete_trigger\` to remove stale triggers.

Variable mapping note:

- Keep \`variable_mapping_json\` paths simple (\`$.field\`), since extraction is shallow.

## Understand workflow execution context

Workflow runs do not execute in the orchestrator sandbox.

Execution context behavior:

1. A workflow session is created as a dedicated session (\`purpose: workflow\`) and initially hibernated.
2. \`WorkflowExecutorDO\` wakes/boots that workflow sandbox when enqueue/resume happens.
3. The executor dispatches a workflow-run prompt into that workflow session.

Repository context behavior:

- Repo context is stored in \`session_git_state\` for the workflow session.
- Executor injects \`REPO_URL\`, \`REPO_BRANCH\`, \`REPO_REF\` env vars into the sandbox.
- Sandbox startup clones \`REPO_URL\` into \`/workspace/<repo>\`, checks out branch/ref when provided, and sets working directory to the clone.

## Author workflow definitions with current runtime behavior

Minimum requirement:

- \`workflow.steps\` must be a non-empty array.
- Each step must have \`id\` (string), \`name\` (string), and \`type\` (string).

Valid step types: \`bash\`, \`tool\`, \`approval\`, \`conditional\`, \`parallel\`, \`agent\`, \`agent_message\`.

### \`bash\` step (preferred for shell commands)

Use \`type: "bash"\` for shell commands. This is a first-class step type.

Required fields:
- \`command\` (string): The shell command to execute.

Optional fields:
- \`description\` (string): Human-readable description of what this command does.
- \`cwd\` (string): Working directory.
- \`timeoutMs\` (number): Timeout in milliseconds (default 120000, max 600000).
- \`outputVariable\` (string): Variable name to store command output.

Example:
\`\`\`json
{
  "id": "1",
  "name": "Run tests",
  "type": "bash",
  "command": "npm test",
  "description": "Run the test suite"
}
\`\`\`

**Do NOT use \`type: "tool"\` with \`tool: "bash"\` for shell commands.** Use \`type: "bash"\` instead.

### \`tool\` step

For non-bash tools only. Requires \`tool\` (string) and optionally \`arguments\` (object).

### \`approval\` step

Pauses execution and waits for human approval.

Optional fields:
- \`prompt\` (string): Message shown to the approver.

### \`conditional\` step

Evaluates a condition and runs \`then\` or \`else\` branch.

Required fields:
- \`condition\`: Boolean value, or object like \`{ "variable": "varName", "equals": "value" }\`.

Optional fields:
- \`then\` (array of steps): Steps to run when condition is true.
- \`else\` (array of steps): Steps to run when condition is false.

### \`parallel\` step

Runs nested steps. Requires \`steps\` (array of steps).

### \`agent\` step

Dispatches work to an AI agent.

Optional fields:
- \`goal\` (string): What the agent should accomplish.
- \`context\` (string): Additional context for the agent.

### \`agent_message\` step

Sends a message to the workflow session agent.

Required: Provide message via \`content\` (preferred), or \`message\`, or \`goal\`.

Optional fields:
- \`interrupt\` (boolean).
- \`await_response\` (or \`awaitResponse\`) boolean.
- \`await_timeout_ms\` (or \`awaitTimeoutMs\`) number, minimum 1000.

Behavior:
- Non-await mode sends a message to the current workflow session agent.
- Await mode runs a temporary OpenCode session and returns response text in step output.

### Complete workflow example

\`\`\`json
{
  "steps": [
    {
      "id": "1",
      "name": "Install dependencies",
      "type": "bash",
      "command": "npm install",
      "description": "Install project dependencies"
    },
    {
      "id": "2",
      "name": "Run linter",
      "type": "bash",
      "command": "npm run lint",
      "description": "Check code quality"
    },
    {
      "id": "3",
      "name": "Run tests",
      "type": "bash",
      "command": "npm test",
      "outputVariable": "test_results"
    },
    {
      "id": "4",
      "name": "Approve deployment",
      "type": "approval",
      "prompt": "Tests passed. Deploy to production?"
    },
    {
      "id": "5",
      "name": "Deploy",
      "type": "bash",
      "command": "npm run deploy"
    }
  ]
}
\`\`\`

## Reliable operating playbook

1. Use \`list_workflows\` and \`list_triggers\` before creating/updating to avoid duplicates.
2. Use \`get_workflow\` before patching critical definitions.
3. Use \`run_workflow\` or \`run_trigger\` for tests.
4. Use \`debug_execution\` first for incidents.
5. Use fresh \`resume_token\` from \`get_execution\` before \`approve_execution\`.
6. Use \`cancel_execution\` when state is inconsistent, then rerun cleanly.
7. Use \`list_workflow_history\` and \`rollback_workflow\` for safe recovery.
`, sortOrder: 0 },
    ],
  },
];
