/**
 * Auto-discovery script for integration & channel plugin packages.
 *
 * Reads packages/worker/package.json, finds @valet/actions-* and
 * @valet/channel-* workspace deps, then generates:
 *   - src/integrations/packages.ts
 *   - src/channels/packages.ts
 *
 * Run: bun packages/worker/scripts/generate-plugin-registry.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const workerRoot = resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(resolve(workerRoot, 'package.json'), 'utf-8'));
// Only reads `dependencies` — plugin packages MUST be listed there, not in devDependencies.
// Wrangler bundles from dependencies at deploy time; devDependencies are not available in production.
const allDeps = Object.keys(pkg.dependencies ?? {});

const actionPackages = allDeps.filter((d) => d.startsWith('@valet/actions-')).sort();
const channelPackages = allDeps.filter((d) => d.startsWith('@valet/channel-')).sort();

const HEADER = '// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit\n';

// ── Integration packages ────────────────────────────────────────────────────

const integrationsLines = [
  HEADER,
  "import type { IntegrationPackage } from '@valet/sdk';",
  ...actionPackages.map((name, i) => `import pkg${i} from '${name}';`),
  '',
  `export const installedIntegrations: IntegrationPackage[] = [${actionPackages.map((_, i) => `pkg${i}`).join(', ')}];`,
  '',
];

writeFileSync(resolve(workerRoot, 'src/integrations/packages.ts'), integrationsLines.join('\n'));

// ── Channel packages ────────────────────────────────────────────────────────

const channelsLines = [
  HEADER,
  "import type { ChannelPackage } from '@valet/sdk';",
  ...channelPackages.map((name, i) => `import pkg${i} from '${name}';`),
  '',
  `export const installedChannels: ChannelPackage[] = [${channelPackages.map((_, i) => `pkg${i}`).join(', ')}];`,
  '',
];

writeFileSync(resolve(workerRoot, 'src/channels/packages.ts'), channelsLines.join('\n'));

console.log(
  `Generated plugin registries: ${actionPackages.length} integration(s), ${channelPackages.length} channel(s)`,
);
