/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrchestratorRouteImport } from './routes/orchestrator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations/index'
import { Route as WorkflowsExecutionsRouteImport } from './routes/workflows/executions'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as SettingsUsageRouteImport } from './routes/settings/usage'
import { Route as SettingsPersonasRouteImport } from './routes/settings/personas'
import { Route as SettingsAdminRouteImport } from './routes/settings/admin'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as InviteCodeRouteImport } from './routes/invite/$code'
import { Route as IntegrationsCallbackRouteImport } from './routes/integrations/callback'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as AutomationWorkflowsIndexRouteImport } from './routes/automation/workflows/index'
import { Route as AutomationTriggersIndexRouteImport } from './routes/automation/triggers/index'
import { Route as AutomationExecutionsIndexRouteImport } from './routes/automation/executions/index'
import { Route as SessionsJoinTokenRouteImport } from './routes/sessions/join/$token'
import { Route as AutomationWorkflowsWorkflowIdRouteImport } from './routes/automation/workflows/$workflowId'
import { Route as SessionsSessionIdThreadsIndexRouteImport } from './routes/sessions/$sessionId/threads/index'
import { Route as SessionsSessionIdThreadsThreadIdRouteImport } from './routes/sessions/$sessionId/threads/$threadId'

const OrchestratorRoute = OrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsExecutionsRoute = WorkflowsExecutionsRouteImport.update({
  id: '/workflows/executions',
  path: '/workflows/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/settings/usage',
  path: '/settings/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPersonasRoute = SettingsPersonasRouteImport.update({
  id: '/settings/personas',
  path: '/settings/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAdminRoute = SettingsAdminRouteImport.update({
  id: '/settings/admin',
  path: '/settings/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsCallbackRoute = IntegrationsCallbackRouteImport.update({
  id: '/integrations/callback',
  path: '/integrations/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)
const AutomationWorkflowsIndexRoute =
  AutomationWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AutomationRoute,
  } as any)
const AutomationTriggersIndexRoute = AutomationTriggersIndexRouteImport.update({
  id: '/triggers/',
  path: '/triggers/',
  getParentRoute: () => AutomationRoute,
} as any)
const AutomationExecutionsIndexRoute =
  AutomationExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => AutomationRoute,
  } as any)
const SessionsJoinTokenRoute = SessionsJoinTokenRouteImport.update({
  id: '/sessions/join/$token',
  path: '/sessions/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationWorkflowsWorkflowIdRoute =
  AutomationWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => AutomationRoute,
  } as any)
const SessionsSessionIdThreadsIndexRoute = SessionsSessionIdThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)
const SessionsSessionIdThreadsThreadIdRoute = SessionsSessionIdThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orchestrator': typeof OrchestratorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/integrations/callback': typeof IntegrationsCallbackRoute
  '/invite/$code': typeof InviteCodeRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/settings/admin': typeof SettingsAdminRoute
  '/settings/personas': typeof SettingsPersonasRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/executions': typeof WorkflowsExecutionsRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/automation/workflows/$workflowId': typeof AutomationWorkflowsWorkflowIdRoute
  '/sessions/join/$token': typeof SessionsJoinTokenRoute
  '/automation/executions/': typeof AutomationExecutionsIndexRoute
  '/automation/triggers/': typeof AutomationTriggersIndexRoute
  '/automation/workflows/': typeof AutomationWorkflowsIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/$sessionId/threads/': typeof SessionsSessionIdThreadsIndexRoute
  '/sessions/$sessionId/threads/$threadId': typeof SessionsSessionIdThreadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orchestrator': typeof OrchestratorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/integrations/callback': typeof IntegrationsCallbackRoute
  '/invite/$code': typeof InviteCodeRoute
  '/settings/admin': typeof SettingsAdminRoute
  '/settings/personas': typeof SettingsPersonasRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/executions': typeof WorkflowsExecutionsRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/automation/workflows/$workflowId': typeof AutomationWorkflowsWorkflowIdRoute
  '/sessions/join/$token': typeof SessionsJoinTokenRoute
  '/automation/executions': typeof AutomationExecutionsIndexRoute
  '/automation/triggers': typeof AutomationTriggersIndexRoute
  '/automation/workflows': typeof AutomationWorkflowsIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/sessions/$sessionId/threads': typeof SessionsSessionIdThreadsIndexRoute
  '/sessions/$sessionId/threads/$threadId': typeof SessionsSessionIdThreadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orchestrator': typeof OrchestratorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/integrations/callback': typeof IntegrationsCallbackRoute
  '/invite/$code': typeof InviteCodeRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/settings/admin': typeof SettingsAdminRoute
  '/settings/personas': typeof SettingsPersonasRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/executions': typeof WorkflowsExecutionsRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/automation/workflows/$workflowId': typeof AutomationWorkflowsWorkflowIdRoute
  '/sessions/join/$token': typeof SessionsJoinTokenRoute
  '/automation/executions/': typeof AutomationExecutionsIndexRoute
  '/automation/triggers/': typeof AutomationTriggersIndexRoute
  '/automation/workflows/': typeof AutomationWorkflowsIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/$sessionId/threads/': typeof SessionsSessionIdThreadsIndexRoute
  '/sessions/$sessionId/threads/$threadId': typeof SessionsSessionIdThreadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/inbox'
    | '/login'
    | '/onboarding'
    | '/orchestrator'
    | '/auth/callback'
    | '/integrations/callback'
    | '/invite/$code'
    | '/sessions/$sessionId'
    | '/settings/admin'
    | '/settings/personas'
    | '/settings/usage'
    | '/workflows/$workflowId'
    | '/workflows/executions'
    | '/integrations/'
    | '/sessions/'
    | '/settings/'
    | '/workflows/'
    | '/automation/workflows/$workflowId'
    | '/sessions/join/$token'
    | '/automation/executions/'
    | '/automation/triggers/'
    | '/automation/workflows/'
    | '/sessions/$sessionId/'
    | '/sessions/$sessionId/threads/'
    | '/sessions/$sessionId/threads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/inbox'
    | '/login'
    | '/onboarding'
    | '/orchestrator'
    | '/auth/callback'
    | '/integrations/callback'
    | '/invite/$code'
    | '/settings/admin'
    | '/settings/personas'
    | '/settings/usage'
    | '/workflows/$workflowId'
    | '/workflows/executions'
    | '/integrations'
    | '/sessions'
    | '/settings'
    | '/workflows'
    | '/automation/workflows/$workflowId'
    | '/sessions/join/$token'
    | '/automation/executions'
    | '/automation/triggers'
    | '/automation/workflows'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/threads'
    | '/sessions/$sessionId/threads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/inbox'
    | '/login'
    | '/onboarding'
    | '/orchestrator'
    | '/auth/callback'
    | '/integrations/callback'
    | '/invite/$code'
    | '/sessions/$sessionId'
    | '/settings/admin'
    | '/settings/personas'
    | '/settings/usage'
    | '/workflows/$workflowId'
    | '/workflows/executions'
    | '/integrations/'
    | '/sessions/'
    | '/settings/'
    | '/workflows/'
    | '/automation/workflows/$workflowId'
    | '/sessions/join/$token'
    | '/automation/executions/'
    | '/automation/triggers/'
    | '/automation/workflows/'
    | '/sessions/$sessionId/'
    | '/sessions/$sessionId/threads/'
    | '/sessions/$sessionId/threads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRouteWithChildren
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrchestratorRoute: typeof OrchestratorRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  IntegrationsCallbackRoute: typeof IntegrationsCallbackRoute
  InviteCodeRoute: typeof InviteCodeRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
  SettingsAdminRoute: typeof SettingsAdminRoute
  SettingsPersonasRoute: typeof SettingsPersonasRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  WorkflowsExecutionsRoute: typeof WorkflowsExecutionsRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  SessionsJoinTokenRoute: typeof SessionsJoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orchestrator': {
      id: '/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof OrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/executions': {
      id: '/workflows/executions'
      path: '/workflows/executions'
      fullPath: '/workflows/executions'
      preLoaderRoute: typeof WorkflowsExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/settings/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/personas': {
      id: '/settings/personas'
      path: '/settings/personas'
      fullPath: '/settings/personas'
      preLoaderRoute: typeof SettingsPersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/admin': {
      id: '/settings/admin'
      path: '/settings/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof SettingsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/callback': {
      id: '/integrations/callback'
      path: '/integrations/callback'
      fullPath: '/integrations/callback'
      preLoaderRoute: typeof IntegrationsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/sessions/$sessionId/threads/': {
      id: '/sessions/$sessionId/threads/'
      path: '/threads'
      fullPath: '/sessions/$sessionId/threads/'
      preLoaderRoute: typeof SessionsSessionIdThreadsIndexRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/sessions/$sessionId/threads/$threadId': {
      id: '/sessions/$sessionId/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/sessions/$sessionId/threads/$threadId'
      preLoaderRoute: typeof SessionsSessionIdThreadsThreadIdRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/automation/workflows/': {
      id: '/automation/workflows/'
      path: '/workflows'
      fullPath: '/automation/workflows/'
      preLoaderRoute: typeof AutomationWorkflowsIndexRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/automation/triggers/': {
      id: '/automation/triggers/'
      path: '/triggers'
      fullPath: '/automation/triggers/'
      preLoaderRoute: typeof AutomationTriggersIndexRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/automation/executions/': {
      id: '/automation/executions/'
      path: '/executions'
      fullPath: '/automation/executions/'
      preLoaderRoute: typeof AutomationExecutionsIndexRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/sessions/join/$token': {
      id: '/sessions/join/$token'
      path: '/sessions/join/$token'
      fullPath: '/sessions/join/$token'
      preLoaderRoute: typeof SessionsJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/workflows/$workflowId': {
      id: '/automation/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/automation/workflows/$workflowId'
      preLoaderRoute: typeof AutomationWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AutomationRoute
    }
  }
}

interface AutomationRouteChildren {
  AutomationWorkflowsWorkflowIdRoute: typeof AutomationWorkflowsWorkflowIdRoute
  AutomationExecutionsIndexRoute: typeof AutomationExecutionsIndexRoute
  AutomationTriggersIndexRoute: typeof AutomationTriggersIndexRoute
  AutomationWorkflowsIndexRoute: typeof AutomationWorkflowsIndexRoute
}

const AutomationRouteChildren: AutomationRouteChildren = {
  AutomationWorkflowsWorkflowIdRoute: AutomationWorkflowsWorkflowIdRoute,
  AutomationExecutionsIndexRoute: AutomationExecutionsIndexRoute,
  AutomationTriggersIndexRoute: AutomationTriggersIndexRoute,
  AutomationWorkflowsIndexRoute: AutomationWorkflowsIndexRoute,
}

const AutomationRouteWithChildren = AutomationRoute._addFileChildren(
  AutomationRouteChildren,
)

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
  SessionsSessionIdThreadsIndexRoute: typeof SessionsSessionIdThreadsIndexRoute
  SessionsSessionIdThreadsThreadIdRoute: typeof SessionsSessionIdThreadsThreadIdRoute
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
  SessionsSessionIdThreadsIndexRoute: SessionsSessionIdThreadsIndexRoute,
  SessionsSessionIdThreadsThreadIdRoute: SessionsSessionIdThreadsThreadIdRoute,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRouteWithChildren,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrchestratorRoute: OrchestratorRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  IntegrationsCallbackRoute: IntegrationsCallbackRoute,
  InviteCodeRoute: InviteCodeRoute,
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
  SettingsAdminRoute: SettingsAdminRoute,
  SettingsPersonasRoute: SettingsPersonasRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  WorkflowsExecutionsRoute: WorkflowsExecutionsRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  SessionsJoinTokenRoute: SessionsJoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
