// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit

import type { IntegrationPackage } from '@valet/sdk';
import pkg0 from '@valet/plugin-cloudflare/actions';
import pkg1 from '@valet/plugin-deepwiki/actions';
import pkg2 from '@valet/plugin-github/actions';
import pkg3 from '@valet/plugin-gmail/actions';
import pkg4 from '@valet/plugin-google-calendar/actions';
import pkg5 from '@valet/plugin-google-workspace/actions';
import pkg6 from '@valet/plugin-linear/actions';
import pkg7 from '@valet/plugin-notion/actions';
import pkg8 from '@valet/plugin-sentry/actions';
import pkg9 from '@valet/plugin-slack/actions';
import pkg10 from '@valet/plugin-stripe/actions';
import pkg11 from '@valet/plugin-typefully/actions';

export const installedIntegrations: IntegrationPackage[] = [pkg0, pkg1, pkg2, pkg3, pkg4, pkg5, pkg6, pkg7, pkg8, pkg9, pkg10, pkg11];
