// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit

import type { RepoProvider } from '@valet/sdk/repos';
import { codestorageRepoProvider as rp0 } from '@valet/plugin-codestorage/repo';
import { githubRepoProvider as rp1 } from '@valet/plugin-github/repo';

export const installedRepoProviders: RepoProvider[] = [rp0, rp1];
